USE [Elixir_LRN];
GO

/* LineLevelData - generated by sql/generate_sql.py. Do not hand-edit. */
IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON s.schema_id = t.schema_id
               WHERE s.name = 'dbo' AND t.name = 'LineLevelData')
BEGIN
    CREATE TABLE [dbo].[LineLevelData]
    (
        [RecordId] BIGINT IDENTITY(1,1) NOT NULL
            CONSTRAINT [PK_LineLevelData] PRIMARY KEY CLUSTERED,
        [FileLogId] BIGINT NOT NULL,
        [RunId] VARCHAR(30) NOT NULL,
        [WeekFolder] NVARCHAR(200) NULL,
        [SourceFullPath] NVARCHAR(1000) NULL,
        [FileName] NVARCHAR(400) NULL,
        [FileType] VARCHAR(20) NOT NULL,
        [RowHash] CHAR(64) NOT NULL,
        [LabID] INT NOT NULL,
        [LabName] NVARCHAR(200) NOT NULL,
        [ClaimID] NVARCHAR(500) NULL,
        [AccessionNumber] NVARCHAR(500) NULL,
        [SourceFileID] NVARCHAR(500) NULL,
        [IngestedOn] NVARCHAR(500) NULL,
        [CsvRowHash] NVARCHAR(500) NULL,
        [PayerName_Raw] NVARCHAR(1000) NULL,
        [PayerName] NVARCHAR(1000) NULL,
        [Payer_Code] NVARCHAR(1000) NULL,
        [Payer_Common_Code] NVARCHAR(1000) NULL,
        [Payer_Group_Code] NVARCHAR(1000) NULL,
        [Global_Payer_ID] NVARCHAR(1000) NULL,
        [PayerType] NVARCHAR(1000) NULL,
        [BillingProvider] NVARCHAR(1000) NULL,
        [ReferringProvider] NVARCHAR(1000) NULL,
        [ClinicName] NVARCHAR(1000) NULL,
        [SalesRepname] NVARCHAR(1000) NULL,
        [PatientID] NVARCHAR(500) NULL,
        [PatientDOB] NVARCHAR(500) NULL,
        [DateofService] NVARCHAR(500) NULL,
        [ChargeEnteredDate] NVARCHAR(500) NULL,
        [FirstBilledDate] NVARCHAR(500) NULL,
        [Panelname] NVARCHAR(1000) NULL,
        [CPTCode] NVARCHAR(500) NULL,
        [Units] NVARCHAR(500) NULL,
        [Modifier] NVARCHAR(500) NULL,
        [POS] NVARCHAR(500) NULL,
        [TOS] NVARCHAR(500) NULL,
        [ChargeAmount] NVARCHAR(500) NULL,
        [ChargeAmountPerUnit] NVARCHAR(500) NULL,
        [AllowedAmount] NVARCHAR(500) NULL,
        [AllowedAmountPerUnit] NVARCHAR(500) NULL,
        [InsurancePayment] NVARCHAR(500) NULL,
        [InsurancePaymentPerUnit] NVARCHAR(500) NULL,
        [PatientPayment] NVARCHAR(500) NULL,
        [PatientPaymentPerUnit] NVARCHAR(500) NULL,
        [TotalPayments] NVARCHAR(500) NULL,
        [InsuranceAdjustments] NVARCHAR(500) NULL,
        [PatientAdjustments] NVARCHAR(500) NULL,
        [TotalAdjustments] NVARCHAR(500) NULL,
        [InsuranceBalance] NVARCHAR(500) NULL,
        [PatientBalance] NVARCHAR(500) NULL,
        [PatientBalancePerUnit] NVARCHAR(500) NULL,
        [TotalBalance] NVARCHAR(500) NULL,
        [CheckDate] NVARCHAR(500) NULL,
        [PostingDate] NVARCHAR(500) NULL,
        [PaymentPostedDate] NVARCHAR(500) NULL,
        [ClaimStatus] NVARCHAR(1000) NULL,
        [PayStatus] NVARCHAR(1000) NULL,
        [DenialCode] NVARCHAR(500) NULL,
        [DenialDate] NVARCHAR(500) NULL,
        [ICDCode] NVARCHAR(MAX) NULL,
        [DaystoDOS] NVARCHAR(500) NULL,
        [RollingDays] NVARCHAR(500) NULL,
        [DaystoBill] NVARCHAR(500) NULL,
        [DaystoPost] NVARCHAR(500) NULL,
        [ICDPointer] NVARCHAR(MAX) NULL,
        [T_F] NVARCHAR(500) NULL,
        [VisitXCptXMod] NVARCHAR(500) NULL,
        [UID] NVARCHAR(500) NULL,
        [PatientFirstName] NVARCHAR(1000) NULL,
        [PatientLastName] NVARCHAR(1000) NULL,
        [AgingDOS] NVARCHAR(500) NULL,
        [ServiceToDate] NVARCHAR(500) NULL,
        [AgingDOE] NVARCHAR(500) NULL,
        [OrderingPhysicianFirstName] NVARCHAR(1000) NULL,
        [ServiceLocationCode] NVARCHAR(500) NULL,
        [PrimarySubId] NVARCHAR(500) NULL,
        [CptXModXUnits] NVARCHAR(MAX) NULL,
        [ServiceChargeAmount] NVARCHAR(500) NULL,
        [LineLevelDenialCode] NVARCHAR(500) NULL,
        [DenialReason] NVARCHAR(MAX) NULL,
        [BillingOption] NVARCHAR(500) NULL,
        [BillStatus] NVARCHAR(1000) NULL,
        [BatchNo] NVARCHAR(500) NULL,
        [CreatedOn] NVARCHAR(500) NULL,
        [CreatedBy] NVARCHAR(500) NULL,
        [UpdatedOn] NVARCHAR(500) NULL,
        [UpdatedBy] NVARCHAR(500) NULL,
        [PaymentPercent] NVARCHAR(500) NULL,
        [InsertedDateTime] DATETIME2(3) NOT NULL
            CONSTRAINT [DF_LineLevelData_InsertedDateTime] DEFAULT (SYSDATETIME())
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_LineLevelData_RunId' AND object_id = OBJECT_ID('dbo.LineLevelData'))
    CREATE NONCLUSTERED INDEX [IX_LineLevelData_RunId] ON [dbo].[LineLevelData] ([RunId]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_LineLevelData_FileLogId' AND object_id = OBJECT_ID('dbo.LineLevelData'))
    CREATE NONCLUSTERED INDEX [IX_LineLevelData_FileLogId] ON [dbo].[LineLevelData] ([FileLogId]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_LineLevelData_Lab_FileType_Run' AND object_id = OBJECT_ID('dbo.LineLevelData'))
    CREATE NONCLUSTERED INDEX [IX_LineLevelData_Lab_FileType_Run] ON [dbo].[LineLevelData] ([LabID], [FileType], [RunId]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_LineLevelData_RowHash' AND object_id = OBJECT_ID('dbo.LineLevelData'))
    CREATE NONCLUSTERED INDEX [IX_LineLevelData_RowHash] ON [dbo].[LineLevelData] ([RowHash]);
GO

/* LineLevelData_Staging - load target for the staging+swap strategy. Same shape, no identity/indexes. */
IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON s.schema_id = t.schema_id
               WHERE s.name = 'dbo' AND t.name = 'LineLevelData_Staging')
BEGIN
    CREATE TABLE [dbo].[LineLevelData_Staging]
    (
        [FileLogId] BIGINT NOT NULL,
        [RunId] VARCHAR(30) NOT NULL,
        [WeekFolder] NVARCHAR(200) NULL,
        [SourceFullPath] NVARCHAR(1000) NULL,
        [FileName] NVARCHAR(400) NULL,
        [FileType] VARCHAR(20) NOT NULL,
        [RowHash] CHAR(64) NOT NULL,
        [LabID] INT NOT NULL,
        [LabName] NVARCHAR(200) NOT NULL,
        [ClaimID] NVARCHAR(500) NULL,
        [AccessionNumber] NVARCHAR(500) NULL,
        [SourceFileID] NVARCHAR(500) NULL,
        [IngestedOn] NVARCHAR(500) NULL,
        [CsvRowHash] NVARCHAR(500) NULL,
        [PayerName_Raw] NVARCHAR(1000) NULL,
        [PayerName] NVARCHAR(1000) NULL,
        [Payer_Code] NVARCHAR(1000) NULL,
        [Payer_Common_Code] NVARCHAR(1000) NULL,
        [Payer_Group_Code] NVARCHAR(1000) NULL,
        [Global_Payer_ID] NVARCHAR(1000) NULL,
        [PayerType] NVARCHAR(1000) NULL,
        [BillingProvider] NVARCHAR(1000) NULL,
        [ReferringProvider] NVARCHAR(1000) NULL,
        [ClinicName] NVARCHAR(1000) NULL,
        [SalesRepname] NVARCHAR(1000) NULL,
        [PatientID] NVARCHAR(500) NULL,
        [PatientDOB] NVARCHAR(500) NULL,
        [DateofService] NVARCHAR(500) NULL,
        [ChargeEnteredDate] NVARCHAR(500) NULL,
        [FirstBilledDate] NVARCHAR(500) NULL,
        [Panelname] NVARCHAR(1000) NULL,
        [CPTCode] NVARCHAR(500) NULL,
        [Units] NVARCHAR(500) NULL,
        [Modifier] NVARCHAR(500) NULL,
        [POS] NVARCHAR(500) NULL,
        [TOS] NVARCHAR(500) NULL,
        [ChargeAmount] NVARCHAR(500) NULL,
        [ChargeAmountPerUnit] NVARCHAR(500) NULL,
        [AllowedAmount] NVARCHAR(500) NULL,
        [AllowedAmountPerUnit] NVARCHAR(500) NULL,
        [InsurancePayment] NVARCHAR(500) NULL,
        [InsurancePaymentPerUnit] NVARCHAR(500) NULL,
        [PatientPayment] NVARCHAR(500) NULL,
        [PatientPaymentPerUnit] NVARCHAR(500) NULL,
        [TotalPayments] NVARCHAR(500) NULL,
        [InsuranceAdjustments] NVARCHAR(500) NULL,
        [PatientAdjustments] NVARCHAR(500) NULL,
        [TotalAdjustments] NVARCHAR(500) NULL,
        [InsuranceBalance] NVARCHAR(500) NULL,
        [PatientBalance] NVARCHAR(500) NULL,
        [PatientBalancePerUnit] NVARCHAR(500) NULL,
        [TotalBalance] NVARCHAR(500) NULL,
        [CheckDate] NVARCHAR(500) NULL,
        [PostingDate] NVARCHAR(500) NULL,
        [PaymentPostedDate] NVARCHAR(500) NULL,
        [ClaimStatus] NVARCHAR(1000) NULL,
        [PayStatus] NVARCHAR(1000) NULL,
        [DenialCode] NVARCHAR(500) NULL,
        [DenialDate] NVARCHAR(500) NULL,
        [ICDCode] NVARCHAR(MAX) NULL,
        [DaystoDOS] NVARCHAR(500) NULL,
        [RollingDays] NVARCHAR(500) NULL,
        [DaystoBill] NVARCHAR(500) NULL,
        [DaystoPost] NVARCHAR(500) NULL,
        [ICDPointer] NVARCHAR(MAX) NULL,
        [T_F] NVARCHAR(500) NULL,
        [VisitXCptXMod] NVARCHAR(500) NULL,
        [UID] NVARCHAR(500) NULL,
        [PatientFirstName] NVARCHAR(1000) NULL,
        [PatientLastName] NVARCHAR(1000) NULL,
        [AgingDOS] NVARCHAR(500) NULL,
        [ServiceToDate] NVARCHAR(500) NULL,
        [AgingDOE] NVARCHAR(500) NULL,
        [OrderingPhysicianFirstName] NVARCHAR(1000) NULL,
        [ServiceLocationCode] NVARCHAR(500) NULL,
        [PrimarySubId] NVARCHAR(500) NULL,
        [CptXModXUnits] NVARCHAR(MAX) NULL,
        [ServiceChargeAmount] NVARCHAR(500) NULL,
        [LineLevelDenialCode] NVARCHAR(500) NULL,
        [DenialReason] NVARCHAR(MAX) NULL,
        [BillingOption] NVARCHAR(500) NULL,
        [BillStatus] NVARCHAR(1000) NULL,
        [BatchNo] NVARCHAR(500) NULL,
        [CreatedOn] NVARCHAR(500) NULL,
        [CreatedBy] NVARCHAR(500) NULL,
        [UpdatedOn] NVARCHAR(500) NULL,
        [UpdatedBy] NVARCHAR(500) NULL,
        [PaymentPercent] NVARCHAR(500) NULL,
        [InsertedDateTime] DATETIME2(3) NOT NULL CONSTRAINT [DF_LineLevelData_Staging_InsertedDateTime] DEFAULT (SYSDATETIME())
    );
END
GO

/* Reconcile [LineLevelData] with the current mapping - additive only. */
IF COL_LENGTH('dbo.LineLevelData', 'ClaimID') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [ClaimID] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'ClaimID' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [ClaimID] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'AccessionNumber') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [AccessionNumber] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'AccessionNumber' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [AccessionNumber] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'SourceFileID') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [SourceFileID] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'SourceFileID' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [SourceFileID] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'IngestedOn') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [IngestedOn] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'IngestedOn' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [IngestedOn] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'CsvRowHash') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [CsvRowHash] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'CsvRowHash' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [CsvRowHash] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'PayerName_Raw') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [PayerName_Raw] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'PayerName_Raw' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [PayerName_Raw] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'PayerName') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [PayerName] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'PayerName' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [PayerName] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'Payer_Code') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [Payer_Code] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'Payer_Code' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [Payer_Code] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'Payer_Common_Code') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [Payer_Common_Code] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'Payer_Common_Code' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [Payer_Common_Code] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'Payer_Group_Code') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [Payer_Group_Code] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'Payer_Group_Code' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [Payer_Group_Code] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'Global_Payer_ID') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [Global_Payer_ID] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'Global_Payer_ID' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [Global_Payer_ID] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'PayerType') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [PayerType] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'PayerType' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [PayerType] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'BillingProvider') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [BillingProvider] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'BillingProvider' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [BillingProvider] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'ReferringProvider') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [ReferringProvider] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'ReferringProvider' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [ReferringProvider] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'ClinicName') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [ClinicName] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'ClinicName' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [ClinicName] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'SalesRepname') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [SalesRepname] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'SalesRepname' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [SalesRepname] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'PatientID') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [PatientID] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'PatientID' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [PatientID] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'PatientDOB') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [PatientDOB] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'PatientDOB' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [PatientDOB] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'DateofService') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [DateofService] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'DateofService' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [DateofService] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'ChargeEnteredDate') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [ChargeEnteredDate] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'ChargeEnteredDate' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [ChargeEnteredDate] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'FirstBilledDate') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [FirstBilledDate] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'FirstBilledDate' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [FirstBilledDate] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'Panelname') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [Panelname] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'Panelname' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [Panelname] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'CPTCode') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [CPTCode] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'CPTCode' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [CPTCode] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'Units') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [Units] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'Units' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [Units] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'Modifier') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [Modifier] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'Modifier' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [Modifier] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'POS') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [POS] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'POS' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [POS] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'TOS') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [TOS] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'TOS' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [TOS] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'ChargeAmount') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [ChargeAmount] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'ChargeAmount' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [ChargeAmount] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'ChargeAmountPerUnit') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [ChargeAmountPerUnit] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'ChargeAmountPerUnit' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [ChargeAmountPerUnit] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'AllowedAmount') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [AllowedAmount] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'AllowedAmount' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [AllowedAmount] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'AllowedAmountPerUnit') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [AllowedAmountPerUnit] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'AllowedAmountPerUnit' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [AllowedAmountPerUnit] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'InsurancePayment') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [InsurancePayment] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'InsurancePayment' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [InsurancePayment] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'InsurancePaymentPerUnit') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [InsurancePaymentPerUnit] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'InsurancePaymentPerUnit' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [InsurancePaymentPerUnit] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'PatientPayment') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [PatientPayment] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'PatientPayment' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [PatientPayment] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'PatientPaymentPerUnit') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [PatientPaymentPerUnit] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'PatientPaymentPerUnit' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [PatientPaymentPerUnit] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'TotalPayments') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [TotalPayments] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'TotalPayments' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [TotalPayments] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'InsuranceAdjustments') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [InsuranceAdjustments] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'InsuranceAdjustments' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [InsuranceAdjustments] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'PatientAdjustments') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [PatientAdjustments] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'PatientAdjustments' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [PatientAdjustments] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'TotalAdjustments') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [TotalAdjustments] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'TotalAdjustments' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [TotalAdjustments] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'InsuranceBalance') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [InsuranceBalance] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'InsuranceBalance' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [InsuranceBalance] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'PatientBalance') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [PatientBalance] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'PatientBalance' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [PatientBalance] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'PatientBalancePerUnit') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [PatientBalancePerUnit] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'PatientBalancePerUnit' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [PatientBalancePerUnit] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'TotalBalance') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [TotalBalance] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'TotalBalance' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [TotalBalance] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'CheckDate') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [CheckDate] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'CheckDate' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [CheckDate] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'PostingDate') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [PostingDate] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'PostingDate' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [PostingDate] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'PaymentPostedDate') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [PaymentPostedDate] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'PaymentPostedDate' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [PaymentPostedDate] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'ClaimStatus') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [ClaimStatus] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'ClaimStatus' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [ClaimStatus] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'PayStatus') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [PayStatus] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'PayStatus' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [PayStatus] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'DenialCode') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [DenialCode] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'DenialCode' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [DenialCode] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'DenialDate') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [DenialDate] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'DenialDate' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [DenialDate] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'ICDCode') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [ICDCode] NVARCHAR(MAX) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'ICDCode' AND c.max_length <> -1)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [ICDCode] NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'DaystoDOS') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [DaystoDOS] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'DaystoDOS' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [DaystoDOS] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'RollingDays') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [RollingDays] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'RollingDays' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [RollingDays] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'DaystoBill') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [DaystoBill] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'DaystoBill' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [DaystoBill] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'DaystoPost') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [DaystoPost] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'DaystoPost' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [DaystoPost] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'ICDPointer') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [ICDPointer] NVARCHAR(MAX) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'ICDPointer' AND c.max_length <> -1)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [ICDPointer] NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'T_F') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [T_F] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'T_F' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [T_F] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'VisitXCptXMod') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [VisitXCptXMod] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'VisitXCptXMod' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [VisitXCptXMod] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'UID') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [UID] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'UID' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [UID] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'PatientFirstName') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [PatientFirstName] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'PatientFirstName' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [PatientFirstName] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'PatientLastName') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [PatientLastName] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'PatientLastName' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [PatientLastName] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'AgingDOS') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [AgingDOS] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'AgingDOS' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [AgingDOS] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'ServiceToDate') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [ServiceToDate] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'ServiceToDate' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [ServiceToDate] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'AgingDOE') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [AgingDOE] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'AgingDOE' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [AgingDOE] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'OrderingPhysicianFirstName') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [OrderingPhysicianFirstName] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'OrderingPhysicianFirstName' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [OrderingPhysicianFirstName] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'ServiceLocationCode') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [ServiceLocationCode] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'ServiceLocationCode' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [ServiceLocationCode] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'PrimarySubId') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [PrimarySubId] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'PrimarySubId' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [PrimarySubId] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'CptXModXUnits') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [CptXModXUnits] NVARCHAR(MAX) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'CptXModXUnits' AND c.max_length <> -1)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [CptXModXUnits] NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'ServiceChargeAmount') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [ServiceChargeAmount] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'ServiceChargeAmount' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [ServiceChargeAmount] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'LineLevelDenialCode') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [LineLevelDenialCode] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'LineLevelDenialCode' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [LineLevelDenialCode] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'DenialReason') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [DenialReason] NVARCHAR(MAX) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'DenialReason' AND c.max_length <> -1)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [DenialReason] NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'BillingOption') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [BillingOption] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'BillingOption' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [BillingOption] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'BillStatus') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [BillStatus] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'BillStatus' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [BillStatus] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'BatchNo') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [BatchNo] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'BatchNo' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [BatchNo] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'CreatedOn') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [CreatedOn] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'CreatedOn' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [CreatedOn] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'CreatedBy') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [CreatedBy] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'CreatedBy' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [CreatedBy] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'UpdatedOn') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [UpdatedOn] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'UpdatedOn' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [UpdatedOn] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'UpdatedBy') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [UpdatedBy] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'UpdatedBy' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [UpdatedBy] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData', 'PaymentPercent') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [PaymentPercent] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData')
           AND c.name = 'PaymentPercent' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData] ALTER COLUMN [PaymentPercent] NVARCHAR(500) NULL;
GO

/* Reconcile [LineLevelData_Staging] with the current mapping - additive only. */
IF COL_LENGTH('dbo.LineLevelData_Staging', 'ClaimID') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [ClaimID] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'ClaimID' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [ClaimID] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'AccessionNumber') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [AccessionNumber] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'AccessionNumber' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [AccessionNumber] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'SourceFileID') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [SourceFileID] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'SourceFileID' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [SourceFileID] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'IngestedOn') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [IngestedOn] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'IngestedOn' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [IngestedOn] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'CsvRowHash') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [CsvRowHash] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'CsvRowHash' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [CsvRowHash] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'PayerName_Raw') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [PayerName_Raw] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'PayerName_Raw' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [PayerName_Raw] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'PayerName') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [PayerName] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'PayerName' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [PayerName] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'Payer_Code') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [Payer_Code] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'Payer_Code' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [Payer_Code] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'Payer_Common_Code') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [Payer_Common_Code] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'Payer_Common_Code' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [Payer_Common_Code] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'Payer_Group_Code') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [Payer_Group_Code] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'Payer_Group_Code' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [Payer_Group_Code] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'Global_Payer_ID') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [Global_Payer_ID] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'Global_Payer_ID' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [Global_Payer_ID] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'PayerType') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [PayerType] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'PayerType' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [PayerType] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'BillingProvider') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [BillingProvider] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'BillingProvider' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [BillingProvider] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'ReferringProvider') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [ReferringProvider] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'ReferringProvider' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [ReferringProvider] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'ClinicName') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [ClinicName] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'ClinicName' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [ClinicName] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'SalesRepname') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [SalesRepname] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'SalesRepname' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [SalesRepname] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'PatientID') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [PatientID] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'PatientID' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [PatientID] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'PatientDOB') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [PatientDOB] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'PatientDOB' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [PatientDOB] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'DateofService') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [DateofService] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'DateofService' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [DateofService] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'ChargeEnteredDate') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [ChargeEnteredDate] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'ChargeEnteredDate' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [ChargeEnteredDate] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'FirstBilledDate') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [FirstBilledDate] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'FirstBilledDate' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [FirstBilledDate] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'Panelname') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [Panelname] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'Panelname' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [Panelname] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'CPTCode') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [CPTCode] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'CPTCode' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [CPTCode] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'Units') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [Units] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'Units' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [Units] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'Modifier') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [Modifier] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'Modifier' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [Modifier] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'POS') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [POS] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'POS' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [POS] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'TOS') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [TOS] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'TOS' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [TOS] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'ChargeAmount') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [ChargeAmount] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'ChargeAmount' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [ChargeAmount] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'ChargeAmountPerUnit') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [ChargeAmountPerUnit] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'ChargeAmountPerUnit' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [ChargeAmountPerUnit] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'AllowedAmount') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [AllowedAmount] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'AllowedAmount' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [AllowedAmount] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'AllowedAmountPerUnit') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [AllowedAmountPerUnit] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'AllowedAmountPerUnit' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [AllowedAmountPerUnit] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'InsurancePayment') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [InsurancePayment] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'InsurancePayment' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [InsurancePayment] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'InsurancePaymentPerUnit') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [InsurancePaymentPerUnit] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'InsurancePaymentPerUnit' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [InsurancePaymentPerUnit] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'PatientPayment') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [PatientPayment] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'PatientPayment' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [PatientPayment] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'PatientPaymentPerUnit') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [PatientPaymentPerUnit] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'PatientPaymentPerUnit' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [PatientPaymentPerUnit] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'TotalPayments') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [TotalPayments] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'TotalPayments' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [TotalPayments] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'InsuranceAdjustments') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [InsuranceAdjustments] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'InsuranceAdjustments' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [InsuranceAdjustments] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'PatientAdjustments') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [PatientAdjustments] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'PatientAdjustments' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [PatientAdjustments] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'TotalAdjustments') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [TotalAdjustments] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'TotalAdjustments' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [TotalAdjustments] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'InsuranceBalance') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [InsuranceBalance] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'InsuranceBalance' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [InsuranceBalance] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'PatientBalance') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [PatientBalance] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'PatientBalance' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [PatientBalance] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'PatientBalancePerUnit') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [PatientBalancePerUnit] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'PatientBalancePerUnit' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [PatientBalancePerUnit] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'TotalBalance') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [TotalBalance] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'TotalBalance' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [TotalBalance] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'CheckDate') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [CheckDate] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'CheckDate' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [CheckDate] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'PostingDate') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [PostingDate] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'PostingDate' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [PostingDate] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'PaymentPostedDate') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [PaymentPostedDate] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'PaymentPostedDate' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [PaymentPostedDate] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'ClaimStatus') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [ClaimStatus] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'ClaimStatus' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [ClaimStatus] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'PayStatus') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [PayStatus] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'PayStatus' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [PayStatus] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'DenialCode') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [DenialCode] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'DenialCode' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [DenialCode] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'DenialDate') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [DenialDate] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'DenialDate' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [DenialDate] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'ICDCode') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [ICDCode] NVARCHAR(MAX) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'ICDCode' AND c.max_length <> -1)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [ICDCode] NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'DaystoDOS') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [DaystoDOS] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'DaystoDOS' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [DaystoDOS] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'RollingDays') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [RollingDays] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'RollingDays' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [RollingDays] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'DaystoBill') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [DaystoBill] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'DaystoBill' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [DaystoBill] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'DaystoPost') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [DaystoPost] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'DaystoPost' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [DaystoPost] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'ICDPointer') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [ICDPointer] NVARCHAR(MAX) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'ICDPointer' AND c.max_length <> -1)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [ICDPointer] NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'T_F') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [T_F] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'T_F' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [T_F] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'VisitXCptXMod') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [VisitXCptXMod] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'VisitXCptXMod' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [VisitXCptXMod] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'UID') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [UID] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'UID' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [UID] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'PatientFirstName') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [PatientFirstName] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'PatientFirstName' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [PatientFirstName] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'PatientLastName') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [PatientLastName] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'PatientLastName' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [PatientLastName] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'AgingDOS') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [AgingDOS] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'AgingDOS' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [AgingDOS] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'ServiceToDate') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [ServiceToDate] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'ServiceToDate' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [ServiceToDate] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'AgingDOE') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [AgingDOE] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'AgingDOE' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [AgingDOE] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'OrderingPhysicianFirstName') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [OrderingPhysicianFirstName] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'OrderingPhysicianFirstName' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [OrderingPhysicianFirstName] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'ServiceLocationCode') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [ServiceLocationCode] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'ServiceLocationCode' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [ServiceLocationCode] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'PrimarySubId') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [PrimarySubId] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'PrimarySubId' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [PrimarySubId] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'CptXModXUnits') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [CptXModXUnits] NVARCHAR(MAX) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'CptXModXUnits' AND c.max_length <> -1)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [CptXModXUnits] NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'ServiceChargeAmount') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [ServiceChargeAmount] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'ServiceChargeAmount' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [ServiceChargeAmount] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'LineLevelDenialCode') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [LineLevelDenialCode] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'LineLevelDenialCode' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [LineLevelDenialCode] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'DenialReason') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [DenialReason] NVARCHAR(MAX) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'DenialReason' AND c.max_length <> -1)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [DenialReason] NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'BillingOption') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [BillingOption] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'BillingOption' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [BillingOption] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'BillStatus') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [BillStatus] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'BillStatus' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [BillStatus] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'BatchNo') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [BatchNo] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'BatchNo' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [BatchNo] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'CreatedOn') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [CreatedOn] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'CreatedOn' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [CreatedOn] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'CreatedBy') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [CreatedBy] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'CreatedBy' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [CreatedBy] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'UpdatedOn') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [UpdatedOn] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'UpdatedOn' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [UpdatedOn] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'UpdatedBy') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [UpdatedBy] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'UpdatedBy' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [UpdatedBy] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.LineLevelData_Staging', 'PaymentPercent') IS NULL
    ALTER TABLE [dbo].[LineLevelData_Staging] ADD [PaymentPercent] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.LineLevelData_Staging')
           AND c.name = 'PaymentPercent' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[LineLevelData_Staging] ALTER COLUMN [PaymentPercent] NVARCHAR(500) NULL;
GO
