/**********************************************************************************************
    LRN Report Engine - Augustus_LRN deployment

    TARGET DATABASE : Augustus_LRN
    BASELINE        : sql/Existing_LineLevel_ClaimLevel_DATA.sql (the schema already running
                      in production for this lab). Every production column is reproduced
                      verbatim - same name, same type, same nullability.
    IDEMPOTENT      : yes. Creates what is missing and adds missing columns only. Never
                      drops, renames, retypes or narrows anything, and never deletes data.

    See SchemaAlignmentReport.md for the column-by-column diff behind this file.

    GENERATED by sql/align_with_production.py - do not hand-edit.
**********************************************************************************************/

USE [Augustus_LRN];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
SET NOCOUNT ON;
GO

/* ---------- LineClaimFileLogs (this worker's file log) ---------- */
GO
/*
    dbo.LineClaimFileLogs - one row per line-level / claim-level file copied into this lab database.

    Run against EVERY lab database. Idempotent, and safe on databases where the table already
    exists: it creates the table only when missing, and adds the outcome columns only when missing.
    Nothing is ever renamed, retyped or dropped.

    Column types match BulkLoad/AuditColumns.cs exactly, because FileLogId / RunId / WeekFolder /
    SourceFullPath / FileName / FileType / LabName are stamped from here onto every row of
    LineLevelData and ClaimLevelData. If you change one, change both.

    USAGE:  sqlcmd -S <server> -d <LabDb> -E -i 02_LineClaimFileLogs.sql
*/


IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON s.schema_id = t.schema_id
               WHERE s.name = 'dbo' AND t.name = 'LineClaimFileLogs')
BEGIN
    CREATE TABLE [dbo].[LineClaimFileLogs]
    (
        [FileLogId]           BIGINT IDENTITY(1,1) NOT NULL
            CONSTRAINT [PK_LineClaimFileLogs] PRIMARY KEY CLUSTERED,
        [RunId]               VARCHAR(30)    NOT NULL,
        [WeekFolder]          NVARCHAR(200)  NULL,
        [LabName]             NVARCHAR(200)  NULL,
        [SourceFullPath]      NVARCHAR(1000) NULL,
        [FileName]            NVARCHAR(400)  NULL,
        [FileType]            VARCHAR(20)    NOT NULL,   -- 'Line Level' / 'Claim Level'
        [FileCreatedDateTime] DATETIME2(3)   NULL,
        [InsertedDateTime]    DATETIME2(3)   NOT NULL
            CONSTRAINT [DF_LineClaimFileLogs_InsertedDateTime] DEFAULT (SYSDATETIME()),

        -- Outcome of the copy. Separate columns rather than overloading an existing one.
        [Status]              VARCHAR(50)    NULL,       -- Success | Failed | Skipped | InProgress
        [RowsCopied]          BIGINT         NULL,
        [ErrorMessage]        NVARCHAR(MAX)  NULL,
        [CompletedDateTime]   DATETIME2(3)   NULL
    );

    PRINT '  created dbo.LineClaimFileLogs';
END
ELSE
BEGIN
    -- Pre-existing table: add only the outcome columns, leaving the original ones untouched.
    IF COL_LENGTH('dbo.LineClaimFileLogs', 'Status') IS NULL
    BEGIN
        ALTER TABLE [dbo].[LineClaimFileLogs] ADD [Status] VARCHAR(50) NULL;
        PRINT '  + Status';
    END

    IF COL_LENGTH('dbo.LineClaimFileLogs', 'RowsCopied') IS NULL
    BEGIN
        ALTER TABLE [dbo].[LineClaimFileLogs] ADD [RowsCopied] BIGINT NULL;
        PRINT '  + RowsCopied';
    END

    IF COL_LENGTH('dbo.LineClaimFileLogs', 'ErrorMessage') IS NULL
    BEGIN
        ALTER TABLE [dbo].[LineClaimFileLogs] ADD [ErrorMessage] NVARCHAR(MAX) NULL;
        PRINT '  + ErrorMessage';
    END

    IF COL_LENGTH('dbo.LineClaimFileLogs', 'CompletedDateTime') IS NULL
    BEGIN
        ALTER TABLE [dbo].[LineClaimFileLogs] ADD [CompletedDateTime] DATETIME2(3) NULL;
        PRINT '  + CompletedDateTime';
    END
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes
               WHERE name = 'IX_LineClaimFileLogs_RunId_FileType'
                 AND object_id = OBJECT_ID('dbo.LineClaimFileLogs'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_LineClaimFileLogs_RunId_FileType]
        ON [dbo].[LineClaimFileLogs] ([RunId], [FileType]);
END
GO

/* ---------- LineLevelData ---------- */
GO
IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON s.schema_id = t.schema_id
               WHERE s.name = 'dbo' AND t.name = 'LineLevelData')
BEGIN
    CREATE TABLE [dbo].[LineLevelData](
        [RecordId] INT IDENTITY(1,1) NOT NULL,
        [FileLogId] NVARCHAR(500) NULL,
        [RunId] NVARCHAR(500) NULL,
        [WeekFolder] NVARCHAR(500) NULL,
        [SourceFullPath] NVARCHAR(1000) NULL,
        [FileName] NVARCHAR(500) NULL,
        [FileType] NVARCHAR(100) NULL,
        [RowHash] NVARCHAR(64) NULL,
        [LabID] NVARCHAR(500) NULL,
        [LabName] NVARCHAR(500) NULL,
        [ClaimID] NVARCHAR(500) NULL,
        [AccessionNumber] NVARCHAR(500) NULL,
        [SourceFileID] NVARCHAR(1000) NULL,
        [IngestedOn] NVARCHAR(500) NULL,
        [CsvRowHash] NVARCHAR(500) NULL,
        [PayerName_Raw] NVARCHAR(500) NULL,
        [PayerName] NVARCHAR(500) NULL,
        [Payer_Code] NVARCHAR(500) NULL,
        [Payer_Common_Code] NVARCHAR(500) NULL,
        [Payer_Group_Code] NVARCHAR(500) NULL,
        [Global_Payer_ID] NVARCHAR(500) NULL,
        [PayerType] NVARCHAR(500) NULL,
        [BillingProvider] NVARCHAR(500) NULL,
        [ReferringProvider] NVARCHAR(500) NULL,
        [ClinicName] NVARCHAR(500) NULL,
        [SalesRepname] NVARCHAR(500) NULL,
        [PatientID] NVARCHAR(500) NULL,
        [PatientDOB] NVARCHAR(500) NULL,
        [DateofService] NVARCHAR(500) NULL,
        [ChargeEnteredDate] NVARCHAR(500) NULL,
        [FirstBilledDate] NVARCHAR(500) NULL,
        [Panelname] NVARCHAR(500) NULL,
        [CPTCode] NVARCHAR(500) NULL,
        [Units] NVARCHAR(500) NULL,
        [Modifier] NVARCHAR(500) NULL,
        [POS] NVARCHAR(500) NULL,
        [TOS] NVARCHAR(500) NULL,
        [ChargeAmount] NVARCHAR(500) NULL,
        [ChargeAmountPerUnit] NVARCHAR(500) NULL,
        [AllowedAmount] NVARCHAR(500) NULL,
        [AllowedAmountPerUnit] NVARCHAR(500) NULL,
        [InsurancePayment] NVARCHAR(500) NULL,
        [InsurancePaymentPerUnit] NVARCHAR(500) NULL,
        [PatientPayment] NVARCHAR(500) NULL,
        [PatientPaymentPerUnit] NVARCHAR(500) NULL,
        [TotalPayments] NVARCHAR(500) NULL,
        [InsuranceAdjustments] NVARCHAR(500) NULL,
        [PatientAdjustments] NVARCHAR(500) NULL,
        [TotalAdjustments] NVARCHAR(500) NULL,
        [InsuranceBalance] NVARCHAR(500) NULL,
        [PatientBalance] NVARCHAR(500) NULL,
        [PatientBalancePerUnit] NVARCHAR(500) NULL,
        [TotalBalance] NVARCHAR(500) NULL,
        [CheckDate] NVARCHAR(500) NULL,
        [PostingDate] NVARCHAR(500) NULL,
        [ClaimStatus] NVARCHAR(500) NULL,
        [PayStatus] NVARCHAR(500) NULL,
        [DenialCode] NVARCHAR(max) NULL,
        [DenialDate] NVARCHAR(500) NULL,
        [ICDCode] NVARCHAR(500) NULL,
        [DaystoDOS] NVARCHAR(500) NULL,
        [RollingDays] NVARCHAR(500) NULL,
        [DaystoBill] NVARCHAR(500) NULL,
        [DaystoPost] NVARCHAR(500) NULL,
        [ICDPointer] NVARCHAR(500) NULL,
        [InsertedDateTime] DATETIME NOT NULL,
        [PaymentPostedDate] NVARCHAR(500) NULL,
        [EncounterPaymentPostedDate] NVARCHAR(500) NULL,
        [PanelNew] NVARCHAR(500) NULL,
        [Source] NVARCHAR(500) NULL,
        [UID] NVARCHAR(500) NULL,
        [Valid] NVARCHAR(100) NULL,
        [PanelCategory] NVARCHAR(500) NULL,
        [PatientName] NVARCHAR(1000) NULL,
        [SubscriberId] NVARCHAR(500) NULL,
        [ClaimAmount] NVARCHAR(500) NULL,
        [Date] NVARCHAR(100) NULL,
        [EnteredStatus] NVARCHAR(500) NULL,
        [BilledStatus] NVARCHAR(500) NULL,
        [CptWithUnits] NVARCHAR(max) NULL,
        [Proc] NVARCHAR(max) NULL,
        [CheqNo] NVARCHAR(500) NULL,
        [AdjAmount] NVARCHAR(500) NULL,
        [InsBalance] NVARCHAR(500) NULL,
        [PatBalance] NVARCHAR(500) NULL,
        [UpdatedDenial] NVARCHAR(max) NULL,
        [CombinedDenial] NVARCHAR(max) NULL,
        [PaymentPercent] NVARCHAR(100) NULL,
        [Loc] NVARCHAR(500) NULL,
        [BillingStatus] NVARCHAR(200) NULL,
        [LBilledDate] NVARCHAR(100) NULL,
        [BProcessDate] NVARCHAR(100) NULL,
        [LineLevelUID] NVARCHAR(500) NULL,
        [InsuranceBalance_Decimal] AS (TRY_CAST([InsuranceBalance] AS [decimal](18,2))) PERSISTED,
        PRIMARY KEY CLUSTERED ([RecordId] ASC)
    );
END
GO

/* InsuranceBalance_Decimal - numeric view of InsuranceBalance, added on every table */
IF COL_LENGTH('dbo.LineLevelData', 'InsuranceBalance_Decimal') IS NULL
   AND COL_LENGTH('dbo.LineLevelData', 'InsuranceBalance') IS NOT NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [InsuranceBalance_Decimal] AS (TRY_CAST([InsuranceBalance] AS [decimal](18,2))) PERSISTED;
GO

IF NOT EXISTS (SELECT 1 FROM sys.default_constraints d
               JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id
               WHERE d.parent_object_id = OBJECT_ID('dbo.LineLevelData') AND c.name = 'InsertedDateTime')
    ALTER TABLE [dbo].[LineLevelData] ADD DEFAULT (getdate()) FOR [InsertedDateTime];
GO

/* columns added on top of the production baseline for LineLevelData */
IF COL_LENGTH('dbo.LineLevelData', 'LineLevelUID') IS NULL
    ALTER TABLE [dbo].[LineLevelData] ADD [LineLevelUID] NVARCHAR(500) NULL;   -- from lab mapping
GO

/* ---------- LineLevelData_Staging - no longer used, dropped to reclaim space ---------- */
GO
IF OBJECT_ID('dbo.LineLevelData_Staging', 'U') IS NOT NULL
BEGIN
    DROP TABLE [dbo].[LineLevelData_Staging];
    PRINT '  dropped dbo.LineLevelData_Staging (superseded by the single-transaction load)';
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_LineLevelData_RunId' AND object_id = OBJECT_ID('dbo.LineLevelData'))
    CREATE NONCLUSTERED INDEX [IX_LineLevelData_RunId] ON [dbo].[LineLevelData] ([RunId]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_LineLevelData_FileLogId' AND object_id = OBJECT_ID('dbo.LineLevelData'))
    CREATE NONCLUSTERED INDEX [IX_LineLevelData_FileLogId] ON [dbo].[LineLevelData] ([FileLogId]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_LineLevelData_Run_FileType' AND object_id = OBJECT_ID('dbo.LineLevelData'))
    CREATE NONCLUSTERED INDEX [IX_LineLevelData_Run_FileType] ON [dbo].[LineLevelData] ([RunId], [FileType]) INCLUDE ([LabID]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_LineLevelData_RowHash' AND object_id = OBJECT_ID('dbo.LineLevelData'))
    CREATE NONCLUSTERED INDEX [IX_LineLevelData_RowHash] ON [dbo].[LineLevelData] ([RowHash]);
GO

/* ---------- ClaimLevelData ---------- */
GO
IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON s.schema_id = t.schema_id
               WHERE s.name = 'dbo' AND t.name = 'ClaimLevelData')
BEGIN
    CREATE TABLE [dbo].[ClaimLevelData](
        [RecordId] INT IDENTITY(1,1) NOT NULL,
        [FileLogId] NVARCHAR(500) NULL,
        [RunId] NVARCHAR(500) NULL,
        [WeekFolder] NVARCHAR(500) NULL,
        [SourceFullPath] NVARCHAR(1000) NULL,
        [FileName] NVARCHAR(500) NULL,
        [FileType] NVARCHAR(100) NULL,
        [RowHash] NVARCHAR(64) NULL,
        [LabID] NVARCHAR(500) NULL,
        [LabName] NVARCHAR(500) NULL,
        [ClaimID] NVARCHAR(500) NULL,
        [AccessionNumber] NVARCHAR(500) NULL,
        [SourceFileID] NVARCHAR(1000) NULL,
        [IngestedOn] NVARCHAR(500) NULL,
        [CsvRowHash] NVARCHAR(500) NULL,
        [PayerName_Raw] NVARCHAR(500) NULL,
        [PayerName] NVARCHAR(500) NULL,
        [Payer_Code] NVARCHAR(500) NULL,
        [Payer_Common_Code] NVARCHAR(500) NULL,
        [Payer_Group_Code] NVARCHAR(500) NULL,
        [Global_Payer_ID] NVARCHAR(500) NULL,
        [PayerType] NVARCHAR(500) NULL,
        [BillingProvider] NVARCHAR(500) NULL,
        [ReferringProvider] NVARCHAR(500) NULL,
        [ClinicName] NVARCHAR(500) NULL,
        [SalesRepname] NVARCHAR(500) NULL,
        [PatientID] NVARCHAR(500) NULL,
        [PatientDOB] NVARCHAR(500) NULL,
        [DateofService] NVARCHAR(500) NULL,
        [ChargeEnteredDate] NVARCHAR(500) NULL,
        [FirstBilledDate] NVARCHAR(500) NULL,
        [Panelname] NVARCHAR(500) NULL,
        [CPTCodeXUnitsXModifier] NVARCHAR(max) NULL,
        [POS] NVARCHAR(500) NULL,
        [TOS] NVARCHAR(500) NULL,
        [ChargeAmount] NVARCHAR(500) NULL,
        [AllowedAmount] NVARCHAR(500) NULL,
        [InsurancePayment] NVARCHAR(500) NULL,
        [PatientPayment] NVARCHAR(500) NULL,
        [TotalPayments] NVARCHAR(500) NULL,
        [InsuranceAdjustments] NVARCHAR(500) NULL,
        [PatientAdjustments] NVARCHAR(500) NULL,
        [TotalAdjustments] NVARCHAR(500) NULL,
        [InsuranceBalance] NVARCHAR(500) NULL,
        [PatientBalance] NVARCHAR(500) NULL,
        [TotalBalance] NVARCHAR(500) NULL,
        [CheckDate] NVARCHAR(500) NULL,
        [ClaimStatus] NVARCHAR(500) NULL,
        [DenialCode] NVARCHAR(max) NULL,
        [ICDCode] NVARCHAR(500) NULL,
        [DaystoDOS] NVARCHAR(500) NULL,
        [RollingDays] NVARCHAR(500) NULL,
        [DaystoBill] NVARCHAR(500) NULL,
        [DaystoPost] NVARCHAR(500) NULL,
        [ICDPointer] NVARCHAR(500) NULL,
        [InsertedDateTime] DATETIME NOT NULL,
        [InsuranceBalance_Decimal] AS (TRY_CAST([InsuranceBalance] AS [decimal](18,2))) PERSISTED,
        [UID] NVARCHAR(500) NULL,
        [Aging] NVARCHAR(100) NULL,
        [PatientName] NVARCHAR(1000) NULL,
        [SubscriberId] NVARCHAR(1000) NULL,
        [EnteredWeek] NVARCHAR(500) NULL,
        [EnteredStatus] NVARCHAR(1000) NULL,
        [BilledWeek] NVARCHAR(500) NULL,
        [BilledStatus] NVARCHAR(max) NULL,
        [PostedWeek] NVARCHAR(500) NULL,
        [ModField] NVARCHAR(100) NULL,
        [ScrubberEditReason] NVARCHAR(max) NULL,
        [CheqNo] NVARCHAR(500) NULL,
        [TimeToPay] NVARCHAR(500) NULL,
        [PaymentPercent] NVARCHAR(100) NULL,
        [FullyPaidCount] NVARCHAR(500) NULL,
        [FullyPaidAmount] NVARCHAR(500) NULL,
        [Adjudicated] NVARCHAR(500) NULL,
        [AdjudicatedAmount] NVARCHAR(500) NULL,
        [Bucket30] NVARCHAR(500) NULL,
        [Bucket30Amount] NVARCHAR(500) NULL,
        [Bucket60] NVARCHAR(500) NULL,
        [Bucket60Amount] NVARCHAR(500) NULL,
        [CPTCodeXUnitsXModifierOrginal] NVARCHAR(max) NULL,
        [PanelNew] NVARCHAR(500) NULL,
        [Source] NVARCHAR(500) NULL,
        [PanelCategory] NVARCHAR(500) NULL,
        [BillingStatus] NVARCHAR(200) NULL,
        [LBilledDate] NVARCHAR(100) NULL,
        [BProcessDate] NVARCHAR(100) NULL,
        [ClaimUID] NVARCHAR(500) NULL,
        [AgingDOE] NVARCHAR(500) NULL,
        [AgingDOS] NVARCHAR(500) NULL,
        [PanelNameLIS] NVARCHAR(500) NULL,
        [PanelNameBasedOnCPT] NVARCHAR(500) NULL,
        PRIMARY KEY CLUSTERED ([RecordId] ASC)
    );
END
GO

/* InsuranceBalance_Decimal - numeric view of InsuranceBalance, added on every table */
IF COL_LENGTH('dbo.ClaimLevelData', 'InsuranceBalance_Decimal') IS NULL
   AND COL_LENGTH('dbo.ClaimLevelData', 'InsuranceBalance') IS NOT NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [InsuranceBalance_Decimal] AS (TRY_CAST([InsuranceBalance] AS [decimal](18,2))) PERSISTED;
GO

IF NOT EXISTS (SELECT 1 FROM sys.default_constraints d
               JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id
               WHERE d.parent_object_id = OBJECT_ID('dbo.ClaimLevelData') AND c.name = 'InsertedDateTime')
    ALTER TABLE [dbo].[ClaimLevelData] ADD DEFAULT (getdate()) FOR [InsertedDateTime];
GO

/* columns added on top of the production baseline for ClaimLevelData */
IF COL_LENGTH('dbo.ClaimLevelData', 'ClaimUID') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [ClaimUID] NVARCHAR(500) NULL;   -- from lab mapping
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'AgingDOE') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [AgingDOE] NVARCHAR(500) NULL;   -- from lab mapping
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'AgingDOS') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [AgingDOS] NVARCHAR(500) NULL;   -- from lab mapping
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'PanelNameLIS') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [PanelNameLIS] NVARCHAR(500) NULL;   -- from lab mapping
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'PanelNameBasedOnCPT') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [PanelNameBasedOnCPT] NVARCHAR(500) NULL;   -- from lab mapping
GO

/* ---------- ClaimLevelData_Staging - no longer used, dropped to reclaim space ---------- */
GO
IF OBJECT_ID('dbo.ClaimLevelData_Staging', 'U') IS NOT NULL
BEGIN
    DROP TABLE [dbo].[ClaimLevelData_Staging];
    PRINT '  dropped dbo.ClaimLevelData_Staging (superseded by the single-transaction load)';
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_ClaimLevelData_RunId' AND object_id = OBJECT_ID('dbo.ClaimLevelData'))
    CREATE NONCLUSTERED INDEX [IX_ClaimLevelData_RunId] ON [dbo].[ClaimLevelData] ([RunId]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_ClaimLevelData_FileLogId' AND object_id = OBJECT_ID('dbo.ClaimLevelData'))
    CREATE NONCLUSTERED INDEX [IX_ClaimLevelData_FileLogId] ON [dbo].[ClaimLevelData] ([FileLogId]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_ClaimLevelData_Run_FileType' AND object_id = OBJECT_ID('dbo.ClaimLevelData'))
    CREATE NONCLUSTERED INDEX [IX_ClaimLevelData_Run_FileType] ON [dbo].[ClaimLevelData] ([RunId], [FileType]) INCLUDE ([LabID]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_ClaimLevelData_RowHash' AND object_id = OBJECT_ID('dbo.ClaimLevelData'))
    CREATE NONCLUSTERED INDEX [IX_ClaimLevelData_RowHash] ON [dbo].[ClaimLevelData] ([RowHash]);
GO

PRINT 'Augustus_LRN deployment complete.';
GO