/**********************************************************************************************
    LRN Report Engine - LRNMaster deployment

    TARGET DATABASE : LRNMaster
    IDEMPOTENT      : yes - safe to run more than once. Creates what is missing, adds
                      missing columns, widens columns that are too small. Never drops,
                      renames, narrows or retypes anything, and never deletes data.

    CONTENTS (in execution order):
      1. ReportRunIdInfoLog table
      2. ReportsWorkflowTracker table + wide view
      3. ReportTypeMaster table + seed (13 report types)
      4. Additive columns on LRN_Run_Log / LRN_Step_Log / ReportRunIdInfoLog / ReportsWorkflowTracker
      5. usp_ReportRunIdInfoLog_Insert
      6. usp_ReportsWorkflowTracker_Upsert

    GENERATED by sql/generate_sql.py - do not hand-edit. Re-run the generator instead.
**********************************************************************************************/
USE [LRNMaster];
GO
SET NOCOUNT ON;
GO

/* ---------- ReportRunIdInfoLog table ---------- */
GO
/*
    LRNMaster.dbo.ReportRunIdInfoLog

    Cross-lab, per-run information log. ADDITIVE: dbo.LRN_Run_Log, dbo.LRN_Step_Log and
    dbo.LRN_Error_Log are unchanged and keep receiving every write they receive today.

    RunId is VARCHAR(30) to match dbo.LRN_Run_Log.RunID from sql/Create_ProcessLogs.sql, which is
    the authoritative RunId type in this repo. (The brief sketched VARCHAR(50); 30 is what the
    existing table actually uses, and a FK-compatible width matters more than the sketch.)

    CreatedOn is IST, matching ProcessLogService.NowIST() and every other timestamp in this
    pipeline. It is written by the application, not defaulted to UTC, so the whole trail is in one
    time zone.

    Idempotent - safe to re-run.
*/

USE [LRNMaster];
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON s.schema_id = t.schema_id
               WHERE s.name = 'dbo' AND t.name = 'ReportRunIdInfoLog')
BEGIN
    CREATE TABLE [dbo].[ReportRunIdInfoLog]
    (
        [ReportRunIdInfoLogId] BIGINT IDENTITY(1,1) NOT NULL
            CONSTRAINT [PK_ReportRunIdInfoLog] PRIMARY KEY CLUSTERED,
        [RunId]        VARCHAR(30)    NOT NULL,
        [ReportType]   VARCHAR(100)   NOT NULL,   -- 'Line Level' / 'Claim Level'
        [SourceSystem] VARCHAR(100)   NOT NULL,   -- lab name, or 'SharePoint'
        [LogType]      VARCHAR(50)    NOT NULL,   -- Start | Info | Warning | Error | End
        [LogMessage]   NVARCHAR(MAX)  NULL,
        [CreatedOn]    DATETIME2(3)   NOT NULL
            CONSTRAINT [DF_ReportRunIdInfoLog_CreatedOn] DEFAULT (SYSDATETIME()),
        [CreatedBy]    VARCHAR(100)   NOT NULL    -- process/account NAME, never an id
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes
               WHERE name = 'IX_ReportRunIdInfoLog_RunId' AND object_id = OBJECT_ID('dbo.ReportRunIdInfoLog'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_ReportRunIdInfoLog_RunId]
        ON [dbo].[ReportRunIdInfoLog] ([RunId])
        INCLUDE ([ReportType], [LogType], [CreatedOn]);
END
GO

-- Error triage across all labs for a run.
IF NOT EXISTS (SELECT 1 FROM sys.indexes
               WHERE name = 'IX_ReportRunIdInfoLog_LogType_CreatedOn' AND object_id = OBJECT_ID('dbo.ReportRunIdInfoLog'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_ReportRunIdInfoLog_LogType_CreatedOn]
        ON [dbo].[ReportRunIdInfoLog] ([LogType], [CreatedOn] DESC)
        INCLUDE ([RunId], [ReportType], [SourceSystem]);
END
GO
GO

/* ---------- ReportsWorkflowTracker table + wide view ---------- */
GO
/*
    LRNMaster.dbo.ReportsWorkflowTracker  (+ dbo.vw_ReportsWorkflowTracker_Wide)

    Modelled on Reports_Workflow_Tracker_v1.0.xlsx, but stored TALL (one row per
    RunId + LabID + ReportName) rather than wide.

    Why tall, when the workbook is wide:
      * The workbook has one Success/Failure column per report (Line Level Master, Claim Level
        Master, LIS Summary, Production Summary, Collection Summary, Denial Report, Executive
        Summary, Clinic Summary, Sales Rep Summary, Coding Validation, Payer Policy Validation,
        Forecasting, Prediction Analysis, Error Log). Adding a report to a wide table is an
        ALTER TABLE plus a code change; adding one here is a new row.
      * Per-report RowCount / StartedOn / CompletedOn / Remarks have nowhere to live in the wide
        shape without 4 columns per report.
      * The unique key makes the write idempotent on re-run, as the brief requires.

    The workbook's exact layout is reproduced by vw_ReportsWorkflowTracker_Wide below, so the
    spreadsheet can still be produced directly from the database.

    Idempotent - safe to re-run.
*/

USE [LRNMaster];
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON s.schema_id = t.schema_id
               WHERE s.name = 'dbo' AND t.name = 'ReportsWorkflowTracker')
BEGIN
    CREATE TABLE [dbo].[ReportsWorkflowTracker]
    (
        [WorkflowTrackerId] BIGINT IDENTITY(1,1) NOT NULL
            CONSTRAINT [PK_ReportsWorkflowTracker] PRIMARY KEY CLUSTERED,
        [RunId]       VARCHAR(30)   NOT NULL,   -- matches dbo.LRN_Run_Log.RunID
        [LabID]       INT           NOT NULL,   -- NOT NULL so the unique key is reliable
        [LabName]     VARCHAR(200)  NULL,
        [WeekFolder]  VARCHAR(200)  NULL,       -- workbook column 'Week'
        [ReportName]  VARCHAR(200)  NOT NULL,   -- 'Line Level Master' / 'Claim Level Master' / ...
        [ReportType]  VARCHAR(100)  NULL,
        [Status]      VARCHAR(50)   NOT NULL,   -- Success | Failed | Skipped | InProgress
        [RowCount]    BIGINT        NULL,
        [StartedOn]   DATETIME2(3)  NULL,
        [CompletedOn] DATETIME2(3)  NULL,       -- workbook column 'Synced on'
        [Remarks]     NVARCHAR(MAX) NULL,
        [CreatedOn]   DATETIME2(3)  NOT NULL
            CONSTRAINT [DF_ReportsWorkflowTracker_CreatedOn] DEFAULT (SYSDATETIME()),
        [CreatedBy]   VARCHAR(100)  NOT NULL,
        CONSTRAINT [UQ_ReportsWorkflowTracker_Run_Report]
            UNIQUE ([RunId], [LabID], [ReportName])
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes
               WHERE name = 'IX_ReportsWorkflowTracker_RunId' AND object_id = OBJECT_ID('dbo.ReportsWorkflowTracker'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_ReportsWorkflowTracker_RunId]
        ON [dbo].[ReportsWorkflowTracker] ([RunId])
        INCLUDE ([LabID], [ReportName], [Status]);
END
GO

/*
    Wide projection matching Reports_Workflow_Tracker_v1.0.xlsx column-for-column.
    Report names not yet produced by any pipeline simply come back NULL.
*/
CREATE OR ALTER VIEW [dbo].[vw_ReportsWorkflowTracker_Wide]
AS
SELECT
    t.LabName                                                        AS [Lab],
    MAX(t.CompletedOn)                                               AS [Synced on],
    t.RunId                                                          AS [RunID],
    MAX(t.WeekFolder)                                                AS [Week],
    MAX(CASE WHEN t.ReportName = 'Line Level Master'        THEN t.Status END) AS [Line Level Master],
    MAX(CASE WHEN t.ReportName = 'Claim Level Master'       THEN t.Status END) AS [Claim Level Master],
    MAX(CASE WHEN t.ReportName = 'LIS Summary'              THEN t.Status END) AS [LIS Summary],
    MAX(CASE WHEN t.ReportName = 'Production Summary'       THEN t.Status END) AS [Production Summary],
    MAX(CASE WHEN t.ReportName = 'Collection Summary'       THEN t.Status END) AS [Collection Summary],
    MAX(CASE WHEN t.ReportName = 'Denial Report'            THEN t.Status END) AS [Denial Report],
    MAX(CASE WHEN t.ReportName = 'Executive Summary'        THEN t.Status END) AS [Executive Summary],
    MAX(CASE WHEN t.ReportName = 'Clinic Summary'           THEN t.Status END) AS [Clinic Summary],
    MAX(CASE WHEN t.ReportName = 'Sales Rep Summary'        THEN t.Status END) AS [Sales Rep Summary],
    MAX(CASE WHEN t.ReportName = 'Coding Validation'        THEN t.Status END) AS [Coding Validation],
    MAX(CASE WHEN t.ReportName = 'Payer Policy Validation'  THEN t.Status END) AS [Payer Policy Validation],
    MAX(CASE WHEN t.ReportName = 'Forecasting'              THEN t.Status END) AS [Forecasting],
    MAX(CASE WHEN t.ReportName = 'Prediction Analysis'      THEN t.Status END) AS [Prediction Analysis],
    MAX(CASE WHEN t.ReportName = 'Error Log'                THEN t.Status END) AS [Error Log]
FROM dbo.ReportsWorkflowTracker AS t
GROUP BY t.RunId, t.LabID, t.LabName;
GO
GO

/* ---------- ReportTypeMaster table + seed (13 report types) ---------- */
GO
/*
    LRNMaster.dbo.ReportTypeMaster

    Master list of the report types tracked in ReportsWorkflowTracker. The names match the column
    headers of Reports_Workflow_Tracker_v1.0.xlsx exactly, so a report name sent by a developer
    resolves without any translation.

    ReportTypeName is UNIQUE - it is the natural key developers send, and the workflow tracker
    procedure resolves ReportTypeId from it.

    Idempotent: safe to re-run. Re-running re-activates and re-seeds any missing type but never
    deletes or renumbers an existing one, so foreign keys stay valid.
*/

USE [LRNMaster];
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON s.schema_id = t.schema_id
               WHERE s.name = 'dbo' AND t.name = 'ReportTypeMaster')
BEGIN
    CREATE TABLE [dbo].[ReportTypeMaster]
    (
        [ReportTypeId]   INT IDENTITY(1,1) NOT NULL
            CONSTRAINT [PK_ReportTypeMaster] PRIMARY KEY CLUSTERED,
        [ReportTypeName] VARCHAR(200)  NOT NULL,
        [IsActive]       BIT           NOT NULL
            CONSTRAINT [DF_ReportTypeMaster_IsActive] DEFAULT (1),
        [CreatedOn]      DATETIME2(3)  NOT NULL
            CONSTRAINT [DF_ReportTypeMaster_CreatedOn] DEFAULT (GETDATE()),
        CONSTRAINT [UQ_ReportTypeMaster_Name] UNIQUE ([ReportTypeName])
    );
END
GO

/* Seed / re-seed. MERGE so re-running adds anything new without touching existing ids. */
MERGE dbo.ReportTypeMaster AS target
USING (VALUES
        ('Line Level Master'),
        ('Claim Level Master'),
        ('LIS Summary'),
        ('Production Summary'),
        ('Collection Summary'),
        ('Denial Report'),
        ('Executive Summary'),
        ('Clinic Summary'),
        ('Sales Rep Summary'),
        ('Coding Validation'),
        ('Payer Policy Validation'),
        ('Forecasting'),
        ('Prediction Analysis')
      ) AS source (ReportTypeName)
    ON target.ReportTypeName = source.ReportTypeName
WHEN MATCHED AND target.IsActive = 0 THEN
    UPDATE SET IsActive = 1
WHEN NOT MATCHED BY TARGET THEN
    INSERT (ReportTypeName, IsActive) VALUES (source.ReportTypeName, 1);
GO
GO

/* ---------- Additive columns on LRN_Run_Log / LRN_Step_Log / ReportRunIdInfoLog / ReportsWorkflowTracker ---------- */
GO
/*
    Additive column migration. Nothing is renamed, retyped or dropped.

      dbo.LRN_Run_Log            + LabId, + WeekFolder
      dbo.LRN_Step_Log           + LabId
      dbo.ReportRunIdInfoLog     + SourceFileName
      dbo.ReportsWorkflowTracker + ReportTypeId  (FK -> dbo.ReportTypeMaster)

    LabId and WeekFolder are added to LRN_Run_Log because usp_ReportsWorkflowTracker_Upsert reads
    them from there: a developer sends only a RunId and the procedure fills in the lab context.
    Both tables previously carried LabName only.

    Existing rows are backfilled where the lab can be identified unambiguously by name.

    Run 03_ReportTypeMaster.sql first (the FK below depends on it).
    Idempotent - safe to re-run.
*/

USE [LRNMaster];
GO
SET NOCOUNT ON;
GO

/* ---------- dbo.LRN_Run_Log ---------- */
IF COL_LENGTH('dbo.LRN_Run_Log', 'LabId') IS NULL
BEGIN
    ALTER TABLE [dbo].[LRN_Run_Log] ADD [LabId] INT NULL;
    PRINT 'LRN_Run_Log + LabId';
END
GO

IF COL_LENGTH('dbo.LRN_Run_Log', 'WeekFolder') IS NULL
BEGIN
    ALTER TABLE [dbo].[LRN_Run_Log] ADD [WeekFolder] VARCHAR(200) NULL;
    PRINT 'LRN_Run_Log + WeekFolder';
END
GO

/* ---------- dbo.LRN_Step_Log ---------- */
IF COL_LENGTH('dbo.LRN_Step_Log', 'LabId') IS NULL
BEGIN
    ALTER TABLE [dbo].[LRN_Step_Log] ADD [LabId] INT NULL;
    PRINT 'LRN_Step_Log + LabId';
END
GO

/* ---------- dbo.ReportRunIdInfoLog ---------- */
IF COL_LENGTH('dbo.ReportRunIdInfoLog', 'SourceFileName') IS NULL
BEGIN
    ALTER TABLE [dbo].[ReportRunIdInfoLog] ADD [SourceFileName] NVARCHAR(400) NULL;
    PRINT 'ReportRunIdInfoLog + SourceFileName';
END
GO

/* ---------- dbo.ReportsWorkflowTracker ---------- */
IF COL_LENGTH('dbo.ReportsWorkflowTracker', 'ReportTypeId') IS NULL
BEGIN
    ALTER TABLE [dbo].[ReportsWorkflowTracker] ADD [ReportTypeId] INT NULL;
    PRINT 'ReportsWorkflowTracker + ReportTypeId';
END
GO

IF OBJECT_ID('dbo.ReportTypeMaster', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_ReportsWorkflowTracker_ReportType')
BEGIN
    ALTER TABLE [dbo].[ReportsWorkflowTracker] WITH NOCHECK
        ADD CONSTRAINT [FK_ReportsWorkflowTracker_ReportType]
        FOREIGN KEY ([ReportTypeId]) REFERENCES [dbo].[ReportTypeMaster] ([ReportTypeId]);
    PRINT 'ReportsWorkflowTracker + FK_ReportsWorkflowTracker_ReportType';
END
GO

/* ---------- backfill LabId from LabMaster, where the name matches exactly one lab ---------- */
IF OBJECT_ID('dbo.LabMaster', 'U') IS NOT NULL
BEGIN
    UPDATE r
    SET    r.LabId = m.LabId
    FROM   dbo.LRN_Run_Log r
    JOIN   dbo.LabMaster  m ON m.LabName = r.LabName
    WHERE  r.LabId IS NULL;

    PRINT CONCAT('LRN_Run_Log LabId backfilled: ', @@ROWCOUNT);

    UPDATE s
    SET    s.LabId = m.LabId
    FROM   dbo.LRN_Step_Log s
    JOIN   dbo.LabMaster   m ON m.LabName = s.LabName
    WHERE  s.LabId IS NULL;

    PRINT CONCAT('LRN_Step_Log LabId backfilled: ', @@ROWCOUNT);
END
ELSE
BEGIN
    PRINT 'dbo.LabMaster not present - LabId left NULL on existing rows (new rows are stamped by the worker).';
END
GO

/* Lab-scoped reporting over the run log. */
IF NOT EXISTS (SELECT 1 FROM sys.indexes
               WHERE name = 'IX_LRN_Run_Log_LabId' AND object_id = OBJECT_ID('dbo.LRN_Run_Log'))
    CREATE NONCLUSTERED INDEX [IX_LRN_Run_Log_LabId] ON [dbo].[LRN_Run_Log] ([LabId]) INCLUDE ([WeekFolder]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes
               WHERE name = 'IX_LRN_Step_Log_LabId' AND object_id = OBJECT_ID('dbo.LRN_Step_Log'))
    CREATE NONCLUSTERED INDEX [IX_LRN_Step_Log_LabId] ON [dbo].[LRN_Step_Log] ([LabId]);
GO
GO

/* ---------- usp_ReportRunIdInfoLog_Insert ---------- */
GO
/*
    dbo.usp_ReportRunIdInfoLog_Insert

    Public entry point for any team writing to ReportRunIdInfoLog. Callers never touch the table
    directly, so column changes stay behind this contract.

    CALL:
        EXEC dbo.usp_ReportRunIdInfoLog_Insert
             @RunId          = '20260801R0003',
             @ReportType     = 'Line Level Master',
             @SourceSystem   = 'Certus',
             @SourceFileName = '20260801R0003_Certus_Line Level_07.20.2026 to 07.26.2026.csv',
             @LogType        = 'Info',
             @LogMessage     = 'Bulk copy completed. Rows=195161.',
             @CreatedBy      = 'LRN.MasterFileProcessorWorker';

    CreatedOn defaults to GETDATE() - callers do not pass it.

    @LogType must be one of Start / Info / Warning / Error / End. Anything else is rejected rather
    than stored, so the log stays queryable by type.

    @ReportType is free text on purpose: this is a progress log and a caller may want finer-grained
    labels than the master list. When the value does match dbo.ReportTypeMaster the id is resolved
    and stored alongside, so the log can still be joined to the master.

    Never throws for a bad @ReportType - logging must not break a caller's pipeline. It throws only
    for a missing @RunId or an invalid @LogType, which are caller bugs worth surfacing.
*/

USE [LRNMaster];
GO

CREATE OR ALTER PROCEDURE [dbo].[usp_ReportRunIdInfoLog_Insert]
    @RunId          VARCHAR(30),
    @ReportType     VARCHAR(100),
    @SourceSystem   VARCHAR(100),
    @SourceFileName NVARCHAR(400) = NULL,
    @LogType        VARCHAR(50),
    @LogMessage     NVARCHAR(MAX) = NULL,
    @CreatedBy      VARCHAR(100),
    @ReportRunIdInfoLogId BIGINT = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    IF NULLIF(LTRIM(RTRIM(@RunId)), '') IS NULL
    BEGIN
        RAISERROR('usp_ReportRunIdInfoLog_Insert: @RunId is required.', 16, 1);
        RETURN;
    END

    IF @LogType NOT IN ('Start', 'Info', 'Warning', 'Error', 'End')
    BEGIN
        RAISERROR('usp_ReportRunIdInfoLog_Insert: @LogType must be Start, Info, Warning, Error or End. Got "%s".', 16, 1, @LogType);
        RETURN;
    END

    DECLARE @ReportTypeId INT =
    (
        SELECT TOP (1) ReportTypeId
        FROM   dbo.ReportTypeMaster
        WHERE  ReportTypeName = @ReportType AND IsActive = 1
    );

    INSERT INTO dbo.ReportRunIdInfoLog
        (RunId, ReportType, SourceSystem, SourceFileName, LogType, LogMessage, CreatedBy, CreatedOn)
    VALUES
        (LTRIM(RTRIM(@RunId)), @ReportType, @SourceSystem, @SourceFileName,
         @LogType, @LogMessage, @CreatedBy, GETDATE());

    SET @ReportRunIdInfoLogId = SCOPE_IDENTITY();
END
GO

GRANT EXECUTE ON [dbo].[usp_ReportRunIdInfoLog_Insert] TO [public];
GO
GO

/* ---------- usp_ReportsWorkflowTracker_Upsert ---------- */
GO
/*
    dbo.usp_ReportsWorkflowTracker_Upsert

    Public entry point for any team recording a report outcome against a run.

    The caller sends a RunId and a ReportName. Everything else about the lab is looked up here:

        LabId, LabName, WeekFolder   <-  dbo.LRN_Run_Log  (by RunId)
        ReportTypeId, ReportType     <-  dbo.ReportTypeMaster (by ReportName)

    so no two teams have to agree on how to spell a lab or a report.

    CALL:
        EXEC dbo.usp_ReportsWorkflowTracker_Upsert
             @RunId       = '20260801R0003',
             @ReportName  = 'Line Level Master',
             @Status      = 'Success',
             @RowCount    = 195161,
             @StartedOn   = '2026-08-01T10:15:00',
             @CompletedOn = '2026-08-01T10:15:23',
             @Remarks     = NULL,
             @CreatedBy   = 'LRN.MasterFileProcessorWorker';

    CreatedOn defaults to GETDATE() - callers do not pass it.

    UPSERT on (RunId, LabID, ReportName): re-running a report for the same run updates the existing
    row instead of duplicating it. StartedOn is preserved from the first call so a later
    Success/Failed update does not erase when the work actually began.

    Validation is strict here, unlike the info-log procedure: this table drives the workflow
    dashboard, so a misspelt report name must fail loudly rather than create a phantom row.
*/

USE [LRNMaster];
GO

CREATE OR ALTER PROCEDURE [dbo].[usp_ReportsWorkflowTracker_Upsert]
    @RunId       VARCHAR(30),
    @ReportName  VARCHAR(200),
    @Status      VARCHAR(50),
    @RowCount    BIGINT        = NULL,
    @StartedOn   DATETIME2(3)  = NULL,
    @CompletedOn DATETIME2(3)  = NULL,
    @Remarks     NVARCHAR(MAX) = NULL,
    @CreatedBy   VARCHAR(100),
    @LabId       INT           = NULL,   -- optional override when the run log has no lab yet
    @WeekFolder  VARCHAR(200)  = NULL    -- optional override
AS
BEGIN
    SET NOCOUNT ON;

    IF NULLIF(LTRIM(RTRIM(@RunId)), '') IS NULL
    BEGIN
        RAISERROR('usp_ReportsWorkflowTracker_Upsert: @RunId is required.', 16, 1);
        RETURN;
    END

    IF @Status NOT IN ('Success', 'Failed', 'Skipped', 'InProgress')
    BEGIN
        RAISERROR('usp_ReportsWorkflowTracker_Upsert: @Status must be Success, Failed, Skipped or InProgress. Got "%s".', 16, 1, @Status);
        RETURN;
    END

    /* ---- report type, from the master by name ---- */
    DECLARE @ReportTypeId INT, @ReportTypeName VARCHAR(200);

    SELECT TOP (1) @ReportTypeId = ReportTypeId, @ReportTypeName = ReportTypeName
    FROM   dbo.ReportTypeMaster
    WHERE  ReportTypeName = @ReportName AND IsActive = 1;

    IF @ReportTypeId IS NULL
    BEGIN
        RAISERROR('usp_ReportsWorkflowTracker_Upsert: "%s" is not an active report in dbo.ReportTypeMaster. Add it there first.', 16, 1, @ReportName);
        RETURN;
    END

    /* ---- lab context, from the run log ---- */
    DECLARE @LabName VARCHAR(200);

    SELECT TOP (1)
           @LabId      = COALESCE(@LabId, r.LabId),
           @LabName    = r.LabName,
           @WeekFolder = COALESCE(@WeekFolder, r.WeekFolder)
    FROM   dbo.LRN_Run_Log r
    WHERE  r.RunID = @RunId
    ORDER BY r.StartTimeIST DESC;

    IF @LabName IS NULL AND @LabId IS NULL
    BEGIN
        RAISERROR('usp_ReportsWorkflowTracker_Upsert: RunId "%s" was not found in dbo.LRN_Run_Log and no @LabId was supplied.', 16, 1, @RunId);
        RETURN;
    END

    -- LabID is part of the natural key, so it cannot be NULL. -1 marks "run log had no lab id yet"
    -- and is still upsertable; it gets corrected on the next call once the run log is stamped.
    SET @LabId = ISNULL(@LabId, -1);

    /* ---- upsert ---- */
    MERGE dbo.ReportsWorkflowTracker WITH (HOLDLOCK) AS target
    USING (SELECT @RunId AS RunId, @LabId AS LabID, @ReportName AS ReportName) AS source
        ON  target.RunId      = source.RunId
        AND target.LabID      = source.LabID
        AND target.ReportName = source.ReportName
    WHEN MATCHED THEN
        UPDATE SET LabName      = ISNULL(@LabName, target.LabName),
                   WeekFolder   = ISNULL(@WeekFolder, target.WeekFolder),
                   ReportTypeId = @ReportTypeId,
                   ReportType   = @ReportTypeName,
                   Status       = @Status,
                   [RowCount]   = ISNULL(@RowCount, target.[RowCount]),
                   StartedOn    = ISNULL(target.StartedOn, @StartedOn),   -- keep the first start
                   CompletedOn  = ISNULL(@CompletedOn, target.CompletedOn),
                   Remarks      = @Remarks
    WHEN NOT MATCHED THEN
        INSERT (RunId, LabID, LabName, WeekFolder, ReportName, ReportTypeId, ReportType,
                Status, [RowCount], StartedOn, CompletedOn, Remarks, CreatedOn, CreatedBy)
        VALUES (@RunId, @LabId, @LabName, @WeekFolder, @ReportName, @ReportTypeId, @ReportTypeName,
                @Status, @RowCount, @StartedOn, @CompletedOn, @Remarks, GETDATE(), @CreatedBy);
END
GO

GRANT EXECUTE ON [dbo].[usp_ReportsWorkflowTracker_Upsert] TO [public];
GO
GO

PRINT 'LRNMaster deployment complete.';
GO
