/**********************************************************************************************
    LRN Report Engine - LRNMaster deployment

    TARGET DATABASE : LRNMaster
    IDEMPOTENT      : yes - safe to run more than once. Creates what is missing, adds
                      missing columns, widens columns that are too small. Never drops,
                      renames, narrows or retypes anything, and never deletes data.

    CONTENTS (in execution order):
      1. ReportRunIdInfoLog table
      2. ReportsWorkflowTracker table + wide view
      3. ReportTypeMaster table + seed (13 report types)
      4. Additive columns on LRN_Run_Log / LRN_Step_Log / ReportRunIdInfoLog / ReportsWorkflowTracker
      5. usp_ReportRunIdInfoLog_Insert
      6. usp_ReportsWorkflowTracker_Upsert
      7. usp_ReportsWorkflowTracker_Pivot (workbook layout)
      8. usp_ReportRunIdInfoLog_Get (read the run log back)
      9. Per-lab RunIds: R<YYYYMMDD><SHORT><NNNN>

    GENERATED by sql/generate_sql.py - do not hand-edit. Re-run the generator instead.
**********************************************************************************************/
USE [LRNMaster];
GO
SET NOCOUNT ON;
GO

/* ---------- ReportRunIdInfoLog table ---------- */
GO
/*
    LRNMaster.dbo.ReportRunIdInfoLog

    Cross-lab, per-run information log. ADDITIVE: dbo.LRN_Run_Log, dbo.LRN_Step_Log and
    dbo.LRN_Error_Log are unchanged and keep receiving every write they receive today.

    RunId is VARCHAR(30) to match dbo.LRN_Run_Log.RunID from sql/Create_ProcessLogs.sql, which is
    the authoritative RunId type in this repo. (The brief sketched VARCHAR(50); 30 is what the
    existing table actually uses, and a FK-compatible width matters more than the sketch.)

    CreatedOn is IST, matching ProcessLogService.NowIST() and every other timestamp in this
    pipeline. It is written by the application, not defaulted to UTC, so the whole trail is in one
    time zone.

    Idempotent - safe to re-run.
*/

USE [LRNMaster];
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON s.schema_id = t.schema_id
               WHERE s.name = 'dbo' AND t.name = 'ReportRunIdInfoLog')
BEGIN
    CREATE TABLE [dbo].[ReportRunIdInfoLog]
    (
        [ReportRunIdInfoLogId] BIGINT IDENTITY(1,1) NOT NULL
            CONSTRAINT [PK_ReportRunIdInfoLog] PRIMARY KEY CLUSTERED,
        [RunId]        VARCHAR(30)    NOT NULL,
        [ReportType]   VARCHAR(100)   NOT NULL,   -- 'Line Level' / 'Claim Level'
        [SourceSystem] VARCHAR(100)   NOT NULL,   -- lab name, or 'SharePoint'
        [LogType]      VARCHAR(50)    NOT NULL,   -- Start | Info | Warning | Error | End
        [LogMessage]   NVARCHAR(MAX)  NULL,
        [CreatedOn]    DATETIME2(3)   NOT NULL
            CONSTRAINT [DF_ReportRunIdInfoLog_CreatedOn] DEFAULT (SYSDATETIME()),
        [CreatedBy]    VARCHAR(100)   NOT NULL    -- process/account NAME, never an id
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes
               WHERE name = 'IX_ReportRunIdInfoLog_RunId' AND object_id = OBJECT_ID('dbo.ReportRunIdInfoLog'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_ReportRunIdInfoLog_RunId]
        ON [dbo].[ReportRunIdInfoLog] ([RunId])
        INCLUDE ([ReportType], [LogType], [CreatedOn]);
END
GO

-- Error triage across all labs for a run.
IF NOT EXISTS (SELECT 1 FROM sys.indexes
               WHERE name = 'IX_ReportRunIdInfoLog_LogType_CreatedOn' AND object_id = OBJECT_ID('dbo.ReportRunIdInfoLog'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_ReportRunIdInfoLog_LogType_CreatedOn]
        ON [dbo].[ReportRunIdInfoLog] ([LogType], [CreatedOn] DESC)
        INCLUDE ([RunId], [ReportType], [SourceSystem]);
END
GO
GO

/* ---------- ReportsWorkflowTracker table + wide view ---------- */
GO
/*
    LRNMaster.dbo.ReportsWorkflowTracker  (+ dbo.vw_ReportsWorkflowTracker_Wide)

    Modelled on Reports_Workflow_Tracker_v1.0.xlsx, but stored TALL (one row per
    RunId + LabID + ReportName) rather than wide.

    Why tall, when the workbook is wide:
      * The workbook has one Success/Failure column per report (Line Level Master, Claim Level
        Master, LIS Summary, Production Summary, Collection Summary, Denial Report, Executive
        Summary, Clinic Summary, Sales Rep Summary, Coding Validation, Payer Policy Validation,
        Forecasting, Prediction Analysis, Error Log). Adding a report to a wide table is an
        ALTER TABLE plus a code change; adding one here is a new row.
      * Per-report RowCount / StartedOn / CompletedOn / Remarks have nowhere to live in the wide
        shape without 4 columns per report.
      * The unique key makes the write idempotent on re-run, as the brief requires.

    The workbook's exact layout is reproduced by vw_ReportsWorkflowTracker_Wide below, so the
    spreadsheet can still be produced directly from the database.

    Idempotent - safe to re-run.
*/

USE [LRNMaster];
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON s.schema_id = t.schema_id
               WHERE s.name = 'dbo' AND t.name = 'ReportsWorkflowTracker')
BEGIN
    CREATE TABLE [dbo].[ReportsWorkflowTracker]
    (
        [WorkflowTrackerId] BIGINT IDENTITY(1,1) NOT NULL
            CONSTRAINT [PK_ReportsWorkflowTracker] PRIMARY KEY CLUSTERED,
        [RunId]       VARCHAR(30)   NOT NULL,   -- matches dbo.LRN_Run_Log.RunID
        [LabID]       INT           NOT NULL,   -- NOT NULL so the unique key is reliable
        [LabName]     VARCHAR(200)  NULL,
        [WeekFolder]  VARCHAR(200)  NULL,       -- workbook column 'Week'
        [ReportName]  VARCHAR(200)  NOT NULL,   -- 'Line Level Master' / 'Claim Level Master' / ...
        [ReportType]  VARCHAR(100)  NULL,
        [Status]      VARCHAR(50)   NOT NULL,   -- Success | Failed | Skipped | InProgress
        [RowCount]    BIGINT        NULL,
        [StartedOn]   DATETIME2(3)  NULL,
        [CompletedOn] DATETIME2(3)  NULL,       -- workbook column 'Synced on'
        [Remarks]     NVARCHAR(MAX) NULL,
        [CreatedOn]   DATETIME2(3)  NOT NULL
            CONSTRAINT [DF_ReportsWorkflowTracker_CreatedOn] DEFAULT (SYSDATETIME()),
        [CreatedBy]   VARCHAR(100)  NOT NULL,
        CONSTRAINT [UQ_ReportsWorkflowTracker_Run_Report]
            UNIQUE ([RunId], [LabID], [ReportName])
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes
               WHERE name = 'IX_ReportsWorkflowTracker_RunId' AND object_id = OBJECT_ID('dbo.ReportsWorkflowTracker'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_ReportsWorkflowTracker_RunId]
        ON [dbo].[ReportsWorkflowTracker] ([RunId])
        INCLUDE ([LabID], [ReportName], [Status]);
END
GO

/*
    Wide projection matching Reports_Workflow_Tracker_v1.0.xlsx column-for-column.
    Report names not yet produced by any pipeline simply come back NULL.
*/
CREATE OR ALTER VIEW [dbo].[vw_ReportsWorkflowTracker_Wide]
AS
SELECT
    t.LabName                                                        AS [Lab],
    MAX(t.CompletedOn)                                               AS [Synced on],
    t.RunId                                                          AS [RunID],
    MAX(t.WeekFolder)                                                AS [Week],
    MAX(CASE WHEN t.ReportName = 'Line Level Master'        THEN t.Status END) AS [Line Level Master],
    MAX(CASE WHEN t.ReportName = 'Claim Level Master'       THEN t.Status END) AS [Claim Level Master],
    MAX(CASE WHEN t.ReportName = 'LIS Summary'              THEN t.Status END) AS [LIS Summary],
    MAX(CASE WHEN t.ReportName = 'Production Summary'       THEN t.Status END) AS [Production Summary],
    MAX(CASE WHEN t.ReportName = 'Collection Summary'       THEN t.Status END) AS [Collection Summary],
    MAX(CASE WHEN t.ReportName = 'Denial Report'            THEN t.Status END) AS [Denial Report],
    MAX(CASE WHEN t.ReportName = 'Executive Summary'        THEN t.Status END) AS [Executive Summary],
    MAX(CASE WHEN t.ReportName = 'Clinic Summary'           THEN t.Status END) AS [Clinic Summary],
    MAX(CASE WHEN t.ReportName = 'Sales Rep Summary'        THEN t.Status END) AS [Sales Rep Summary],
    MAX(CASE WHEN t.ReportName = 'Coding Validation'        THEN t.Status END) AS [Coding Validation],
    MAX(CASE WHEN t.ReportName = 'Payer Policy Validation'  THEN t.Status END) AS [Payer Policy Validation],
    MAX(CASE WHEN t.ReportName = 'Forecasting'              THEN t.Status END) AS [Forecasting],
    MAX(CASE WHEN t.ReportName = 'Prediction Analysis'      THEN t.Status END) AS [Prediction Analysis],
    MAX(CASE WHEN t.ReportName = 'Error Log'                THEN t.Status END) AS [Error Log]
FROM dbo.ReportsWorkflowTracker AS t
GROUP BY t.RunId, t.LabID, t.LabName;
GO
GO

/* ---------- ReportTypeMaster table + seed (13 report types) ---------- */
GO
/*
    LRNMaster.dbo.ReportTypeMaster

    Master list of the report types tracked in ReportsWorkflowTracker. The names match the column
    headers of Reports_Workflow_Tracker_v1.0.xlsx exactly, so a report name sent by a developer
    resolves without any translation.

    ReportTypeName is UNIQUE - it is the natural key developers send, and the workflow tracker
    procedure resolves ReportTypeId from it.

    Idempotent: safe to re-run. Re-running re-activates and re-seeds any missing type but never
    deletes or renumbers an existing one, so foreign keys stay valid.
*/

USE [LRNMaster];
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON s.schema_id = t.schema_id
               WHERE s.name = 'dbo' AND t.name = 'ReportTypeMaster')
BEGIN
    CREATE TABLE [dbo].[ReportTypeMaster]
    (
        [ReportTypeId]   INT IDENTITY(1,1) NOT NULL
            CONSTRAINT [PK_ReportTypeMaster] PRIMARY KEY CLUSTERED,
        [ReportTypeName] VARCHAR(200)  NOT NULL,
        [IsActive]       BIT           NOT NULL
            CONSTRAINT [DF_ReportTypeMaster_IsActive] DEFAULT (1),
        -- Column order in the workbook / pivot. NOT the same as ReportTypeId, which is just the
        -- insert order and happened to come out alphabetical.
        [DisplayOrder]   INT           NOT NULL
            CONSTRAINT [DF_ReportTypeMaster_DisplayOrder] DEFAULT (999),
        [CreatedOn]      DATETIME2(3)  NOT NULL
            CONSTRAINT [DF_ReportTypeMaster_CreatedOn] DEFAULT (GETDATE()),
        CONSTRAINT [UQ_ReportTypeMaster_Name] UNIQUE ([ReportTypeName])
    );
END
GO

/* DisplayOrder for databases created before the column existed. */
IF COL_LENGTH('dbo.ReportTypeMaster', 'DisplayOrder') IS NULL
BEGIN
    ALTER TABLE [dbo].[ReportTypeMaster] ADD [DisplayOrder] INT NOT NULL
        CONSTRAINT [DF_ReportTypeMaster_DisplayOrder] DEFAULT (999);
    PRINT 'ReportTypeMaster + DisplayOrder';
END
GO

/*
    Seed / re-seed. The order below is the column order of
    Reports_Workflow_Tracker_v1.0.xlsx, which is how the business reads the dashboard - line level
    and claim level first, then the summaries, then the validations. MERGE so re-running adds
    anything new and corrects DisplayOrder without renumbering existing ids.
*/
MERGE dbo.ReportTypeMaster AS target
USING (VALUES
        ( 1, 'Line Level Master'),
        ( 2, 'Claim Level Master'),
        ( 3, 'LIS Summary'),
        ( 4, 'Production Summary'),
        ( 5, 'Collection Summary'),
        ( 6, 'Denial Report'),
        ( 7, 'Executive Summary'),
        ( 8, 'Clinic Summary'),
        ( 9, 'Sales Rep Summary'),
        (10, 'Coding Validation'),
        (11, 'Payer Policy Validation'),
        (12, 'Forecasting'),
        (13, 'Prediction Analysis'),
        (14, 'Error Log')
      ) AS source (DisplayOrder, ReportTypeName)
    ON target.ReportTypeName = source.ReportTypeName
WHEN MATCHED THEN
    UPDATE SET IsActive = 1, DisplayOrder = source.DisplayOrder
WHEN NOT MATCHED BY TARGET THEN
    INSERT (ReportTypeName, IsActive, DisplayOrder)
    VALUES (source.ReportTypeName, 1, source.DisplayOrder);
GO
GO

/* ---------- Additive columns on LRN_Run_Log / LRN_Step_Log / ReportRunIdInfoLog / ReportsWorkflowTracker ---------- */
GO
/*
    Additive column migration. Nothing is renamed, retyped or dropped.

      dbo.LRN_Run_Log            + LabId, + WeekFolder
      dbo.LRN_Step_Log           + LabId
      dbo.ReportRunIdInfoLog     + SourceFileName
      dbo.ReportsWorkflowTracker + ReportTypeId  (FK -> dbo.ReportTypeMaster)

    LabId and WeekFolder are added to LRN_Run_Log because usp_ReportsWorkflowTracker_Upsert reads
    them from there: a developer sends only a RunId and the procedure fills in the lab context.
    Both tables previously carried LabName only.

    Existing rows are backfilled where the lab can be identified unambiguously by name.

    Run 03_ReportTypeMaster.sql first (the FK below depends on it).
    Idempotent - safe to re-run.
*/

USE [LRNMaster];
GO
SET NOCOUNT ON;
GO

/* ---------- dbo.LRN_Run_Log ---------- */
IF COL_LENGTH('dbo.LRN_Run_Log', 'LabId') IS NULL
BEGIN
    ALTER TABLE [dbo].[LRN_Run_Log] ADD [LabId] INT NULL;
    PRINT 'LRN_Run_Log + LabId';
END
GO

IF COL_LENGTH('dbo.LRN_Run_Log', 'WeekFolder') IS NULL
BEGIN
    ALTER TABLE [dbo].[LRN_Run_Log] ADD [WeekFolder] VARCHAR(200) NULL;
    PRINT 'LRN_Run_Log + WeekFolder';
END
GO

/* ---------- dbo.LRN_Step_Log ---------- */
IF COL_LENGTH('dbo.LRN_Step_Log', 'LabId') IS NULL
BEGIN
    ALTER TABLE [dbo].[LRN_Step_Log] ADD [LabId] INT NULL;
    PRINT 'LRN_Step_Log + LabId';
END
GO

/* ---------- dbo.ReportRunIdInfoLog ---------- */
IF COL_LENGTH('dbo.ReportRunIdInfoLog', 'SourceFileName') IS NULL
BEGIN
    ALTER TABLE [dbo].[ReportRunIdInfoLog] ADD [SourceFileName] NVARCHAR(400) NULL;
    PRINT 'ReportRunIdInfoLog + SourceFileName';
END
GO

/* ---------- dbo.ReportsWorkflowTracker ---------- */
IF COL_LENGTH('dbo.ReportsWorkflowTracker', 'ReportTypeId') IS NULL
BEGIN
    ALTER TABLE [dbo].[ReportsWorkflowTracker] ADD [ReportTypeId] INT NULL;
    PRINT 'ReportsWorkflowTracker + ReportTypeId';
END
GO

IF OBJECT_ID('dbo.ReportTypeMaster', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_ReportsWorkflowTracker_ReportType')
BEGIN
    ALTER TABLE [dbo].[ReportsWorkflowTracker] WITH NOCHECK
        ADD CONSTRAINT [FK_ReportsWorkflowTracker_ReportType]
        FOREIGN KEY ([ReportTypeId]) REFERENCES [dbo].[ReportTypeMaster] ([ReportTypeId]);
    PRINT 'ReportsWorkflowTracker + FK_ReportsWorkflowTracker_ReportType';
END
GO

/* ---------- backfill LabId from dbo.Labs, where the name matches exactly one lab ---------- */
IF OBJECT_ID('dbo.Labs', 'U') IS NOT NULL
BEGIN
    UPDATE r
    SET    r.LabId = m.LabId
    FROM   dbo.LRN_Run_Log r
    JOIN   dbo.Labs   m ON m.LabName = r.LabName
    WHERE  r.LabId IS NULL;

    PRINT CONCAT('LRN_Run_Log LabId backfilled: ', @@ROWCOUNT);

    UPDATE s
    SET    s.LabId = m.LabId
    FROM   dbo.LRN_Step_Log s
    JOIN   dbo.Labs   m ON m.LabName = s.LabName
    WHERE  s.LabId IS NULL;

    PRINT CONCAT('LRN_Step_Log LabId backfilled: ', @@ROWCOUNT);
END
ELSE
BEGIN
    PRINT 'dbo.Labs not present - LabId left NULL on existing rows (new rows are stamped by the worker).';
END
GO

/* Lab-scoped reporting over the run log. */
IF NOT EXISTS (SELECT 1 FROM sys.indexes
               WHERE name = 'IX_LRN_Run_Log_LabId' AND object_id = OBJECT_ID('dbo.LRN_Run_Log'))
    CREATE NONCLUSTERED INDEX [IX_LRN_Run_Log_LabId] ON [dbo].[LRN_Run_Log] ([LabId]) INCLUDE ([WeekFolder]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes
               WHERE name = 'IX_LRN_Step_Log_LabId' AND object_id = OBJECT_ID('dbo.LRN_Step_Log'))
    CREATE NONCLUSTERED INDEX [IX_LRN_Step_Log_LabId] ON [dbo].[LRN_Step_Log] ([LabId]);
GO
GO

/* ---------- usp_ReportRunIdInfoLog_Insert ---------- */
GO
/*
    dbo.usp_ReportRunIdInfoLog_Insert

    Public entry point for any team writing to ReportRunIdInfoLog. Callers never touch the table
    directly, so column changes stay behind this contract.

    CALL:
        EXEC dbo.usp_ReportRunIdInfoLog_Insert
             @RunId          = '20260801R0003',
             @ReportType     = 'Line Level Master',
             @SourceSystem   = 'Certus',
             @SourceFileName = '20260801R0003_Certus_Line Level_07.20.2026 to 07.26.2026.csv',
             @LogType        = 'Info',
             @LogMessage     = 'Bulk copy completed. Rows=195161.',
             @CreatedBy      = 'LRN.MasterFileProcessorWorker';

    CreatedOn defaults to GETDATE() - callers do not pass it.

    @LogType must be one of Start / Info / Warning / Error / End. Anything else is rejected rather
    than stored, so the log stays queryable by type.

    @ReportType is free text on purpose: this is a progress log and a caller may want finer-grained
    labels than the master list. When the value does match dbo.ReportTypeMaster the id is resolved
    and stored alongside, so the log can still be joined to the master.

    Never throws for a bad @ReportType - logging must not break a caller's pipeline. It throws only
    for a missing @RunId or an invalid @LogType, which are caller bugs worth surfacing.
*/

USE [LRNMaster];
GO

CREATE OR ALTER PROCEDURE [dbo].[usp_ReportRunIdInfoLog_Insert]
    @RunId          VARCHAR(30),
    @ReportType     VARCHAR(100),
    @SourceSystem   VARCHAR(100),
    @SourceFileName NVARCHAR(400) = NULL,
    @LogType        VARCHAR(50),
    @LogMessage     NVARCHAR(MAX) = NULL,
    @CreatedBy      VARCHAR(100),
    @ReportRunIdInfoLogId BIGINT = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    IF NULLIF(LTRIM(RTRIM(@RunId)), '') IS NULL
    BEGIN
        RAISERROR('usp_ReportRunIdInfoLog_Insert: @RunId is required.', 16, 1);
        RETURN;
    END

    IF @LogType NOT IN ('Start', 'Info', 'Warning', 'Error', 'End')
    BEGIN
        RAISERROR('usp_ReportRunIdInfoLog_Insert: @LogType must be Start, Info, Warning, Error or End. Got "%s".', 16, 1, @LogType);
        RETURN;
    END

    DECLARE @ReportTypeId INT =
    (
        SELECT TOP (1) ReportTypeId
        FROM   dbo.ReportTypeMaster
        WHERE  ReportTypeName = @ReportType AND IsActive = 1
    );

    INSERT INTO dbo.ReportRunIdInfoLog
        (RunId, ReportType, SourceSystem, SourceFileName, LogType, LogMessage, CreatedBy, CreatedOn)
    VALUES
        (LTRIM(RTRIM(@RunId)), @ReportType, @SourceSystem, @SourceFileName,
         @LogType, @LogMessage, @CreatedBy, GETDATE());

    SET @ReportRunIdInfoLogId = SCOPE_IDENTITY();
END
GO

GRANT EXECUTE ON [dbo].[usp_ReportRunIdInfoLog_Insert] TO [public];
GO
GO

/* ---------- usp_ReportsWorkflowTracker_Upsert ---------- */
GO
/*
    dbo.usp_ReportsWorkflowTracker_Upsert

    Public entry point for any team recording a report outcome against a run.

    The caller sends a RunId and a ReportName. Everything else about the lab is looked up here:

        LabId, LabName, WeekFolder   <-  dbo.LRN_Run_Log  (by RunId)
        WeekFolder (fallback)        <-  dbo.ReportsWorkflowTracker (by RunId)
        ReportTypeId, ReportType     <-  dbo.ReportTypeMaster (by ReportName)

    so no two teams have to agree on how to spell a lab or a report.

    WEEKFOLDER FALLBACK. A caller that does not send @WeekFolder gets it resolved, in order:

        1. dbo.LRN_Run_Log for the RunId
        2. the RunId's existing tracker rows - preferring the same lab, then 'Line Level Master' /
           'Claim Level Master', then the most recent - taking the first non-NULL

    The master file processor stamps WeekFolder on its own two rows, and today the run log often
    holds NULL, so step 2 is what actually fills it in. WeekFolder is a property of the run, not of
    the report, so every report of a run belongs to the same week. Once resolved it also backfills
    any row of that run still holding NULL - and only those, so a value a caller sent is never
    overwritten.

    CALL:
        EXEC dbo.usp_ReportsWorkflowTracker_Upsert
             @RunId       = '20260801R0003',
             @ReportName  = 'Line Level Master',
             @Status      = 'Success',
             @RowCount    = 195161,
             @StartedOn   = '2026-08-01T10:15:00',
             @CompletedOn = '2026-08-01T10:15:23',
             @Remarks     = NULL,
             @CreatedBy   = 'LRN.MasterFileProcessorWorker';

    CreatedOn defaults to GETDATE() - callers do not pass it.

    UPSERT on (RunId, LabID, ReportName): re-running a report for the same run updates the existing
    row instead of duplicating it. StartedOn is preserved from the first call so a later
    Success/Failed update does not erase when the work actually began.

    Validation is strict here, unlike the info-log procedure: this table drives the workflow
    dashboard, so a misspelt report name must fail loudly rather than create a phantom row.
*/

USE [LRNMaster];
GO

CREATE OR ALTER PROCEDURE [dbo].[usp_ReportsWorkflowTracker_Upsert]
    @RunId       VARCHAR(30),
    @ReportName  VARCHAR(200),
    @Status      VARCHAR(50),
    @RowCount    BIGINT        = NULL,
    @StartedOn   DATETIME2(3)  = NULL,
    @CompletedOn DATETIME2(3)  = NULL,
    @Remarks     NVARCHAR(MAX) = NULL,
    @CreatedBy   VARCHAR(100),
    @LabId       INT           = NULL,   -- optional override when the run log has no lab yet
    @WeekFolder  VARCHAR(200)  = NULL    -- optional override
AS
BEGIN
    SET NOCOUNT ON;

    -- An empty string is 'not supplied', not a week folder. Without this the fallback below is
    -- skipped and the row stores '' - which reads as data and is harder to spot than NULL.
    SET @WeekFolder = NULLIF(LTRIM(RTRIM(@WeekFolder)), '');

    IF NULLIF(LTRIM(RTRIM(@RunId)), '') IS NULL
    BEGIN
        RAISERROR('usp_ReportsWorkflowTracker_Upsert: @RunId is required.', 16, 1);
        RETURN;
    END

    IF @Status NOT IN ('Success', 'Failed', 'Skipped', 'InProgress')
    BEGIN
        RAISERROR('usp_ReportsWorkflowTracker_Upsert: @Status must be Success, Failed, Skipped or InProgress. Got "%s".', 16, 1, @Status);
        RETURN;
    END

    /* ---- report type, from the master by name ---- */
    DECLARE @ReportTypeId INT, @ReportTypeName VARCHAR(200);

    SELECT TOP (1) @ReportTypeId = ReportTypeId, @ReportTypeName = ReportTypeName
    FROM   dbo.ReportTypeMaster
    WHERE  ReportTypeName = @ReportName AND IsActive = 1;

    IF @ReportTypeId IS NULL
    BEGIN
        RAISERROR('usp_ReportsWorkflowTracker_Upsert: "%s" is not an active report in dbo.ReportTypeMaster. Add it there first.', 16, 1, @ReportName);
        RETURN;
    END

    /* ---- lab context, from the run log ---- */
    DECLARE @LabName VARCHAR(200);

    SELECT TOP (1)
           @LabId      = COALESCE(@LabId, r.LabId),
           @LabName    = r.LabName,
           @WeekFolder = COALESCE(@WeekFolder, r.WeekFolder)
    FROM   dbo.LRN_Run_Log r
    WHERE  r.RunID = @RunId
    ORDER BY r.StartTimeIST DESC;

    IF @LabName IS NULL AND @LabId IS NULL
    BEGIN
        RAISERROR('usp_ReportsWorkflowTracker_Upsert: RunId "%s" was not found in dbo.LRN_Run_Log and no @LabId was supplied.', 16, 1, @RunId);
        RETURN;
    END

    /*
        ---- WeekFolder fallback: borrow it from the run's own tracker rows ----

        Preference order, first non-NULL wins:
          1. the same lab - a different lab's week folder would be the wrong value, not just a
             stale one
          2. the two master reports, which are the rows the file processor stamps directly
          3. most recently touched

        The lab is a PREFERENCE rather than a filter on purpose. LabID is not reliably identical
        across a run's rows yet - the run log resolves NorthWest to 23 via dbo.Labs while the
        worker still writes 20 from its mapping JSON - and a hard filter would silently return
        nothing in exactly that case.
    */
    IF @WeekFolder IS NULL
    BEGIN
        SELECT TOP (1) @WeekFolder = t.WeekFolder
        FROM   dbo.ReportsWorkflowTracker t
        WHERE  t.RunId = @RunId
          AND  t.WeekFolder IS NOT NULL
        ORDER BY CASE WHEN @LabId IS NOT NULL AND t.LabID = @LabId THEN 0 ELSE 1 END,
                 CASE WHEN t.ReportName IN ('Line Level Master', 'Claim Level Master') THEN 0 ELSE 1 END,
                 COALESCE(t.CompletedOn, t.CreatedOn) DESC,
                 t.WorkflowTrackerId DESC;
    END

    -- LabID is part of the natural key, so it cannot be NULL. -1 marks "run log had no lab id yet"
    -- and is still upsertable; it gets corrected on the next call once the run log is stamped.
    SET @LabId = ISNULL(@LabId, -1);

    /* ---- upsert ---- */
    MERGE dbo.ReportsWorkflowTracker WITH (HOLDLOCK) AS target
    USING (SELECT @RunId AS RunId, @LabId AS LabID, @ReportName AS ReportName) AS source
        ON  target.RunId      = source.RunId
        AND target.LabID      = source.LabID
        AND target.ReportName = source.ReportName
    WHEN MATCHED THEN
        UPDATE SET LabName      = ISNULL(@LabName, target.LabName),
                   WeekFolder   = ISNULL(@WeekFolder, target.WeekFolder),
                   ReportTypeId = @ReportTypeId,
                   ReportType   = @ReportTypeName,
                   Status       = @Status,
                   [RowCount]   = ISNULL(@RowCount, target.[RowCount]),
                   StartedOn    = ISNULL(target.StartedOn, @StartedOn),   -- keep the first start
                   CompletedOn  = ISNULL(@CompletedOn, target.CompletedOn),
                   Remarks      = @Remarks
    WHEN NOT MATCHED THEN
        INSERT (RunId, LabID, LabName, WeekFolder, ReportName, ReportTypeId, ReportType,
                Status, [RowCount], StartedOn, CompletedOn, Remarks, CreatedOn, CreatedBy)
        VALUES (@RunId, @LabId, @LabName, @WeekFolder, @ReportName, @ReportTypeId, @ReportTypeName,
                @Status, @RowCount, @StartedOn, @CompletedOn, @Remarks, GETDATE(), @CreatedBy);

    /*
        Backfill the rest of the run. Reports that logged before the week folder was known are
        sitting on NULL; the value is a property of the run, so it belongs on all of them.

        Strictly WHERE WeekFolder IS NULL - this never overwrites a value someone supplied.
    */
    IF @WeekFolder IS NOT NULL
    BEGIN
        UPDATE dbo.ReportsWorkflowTracker
        SET    WeekFolder = @WeekFolder
        WHERE  RunId      = @RunId
          AND  WeekFolder IS NULL;
    END
END
GO

GRANT EXECUTE ON [dbo].[usp_ReportsWorkflowTracker_Upsert] TO [public];
GO
GO

/* ---------- usp_ReportsWorkflowTracker_Pivot (workbook layout) ---------- */
GO
/*
    dbo.usp_ReportsWorkflowTracker_Pivot

    Renders ReportsWorkflowTracker in the workbook layout: one row per RunId + Lab, with every report
    type as its own column and the status as the value.

        Lab | Synced on | RunID | Week | Line Level Master | Claim Level Master | LIS Summary | ...

    The columns come from dbo.ReportTypeMaster in DisplayOrder, which is the column order of
    Reports_Workflow_Tracker_v1.0.xlsx. Adding a report there adds a column here with no change to
    this procedure; changing DisplayOrder moves it.

    CALL:
        EXEC dbo.usp_ReportsWorkflowTracker_Pivot;                          -- everything
        EXEC dbo.usp_ReportsWorkflowTracker_Pivot @RunId = '20260724R0044'; -- one run
        EXEC dbo.usp_ReportsWorkflowTracker_Pivot @LabId = 4;               -- one lab
        EXEC dbo.usp_ReportsWorkflowTracker_Pivot @FromDate = '2026-07-01', @ToDate = '2026-07-31';

        -- one row per lab
        EXEC dbo.usp_ReportsWorkflowTracker_Pivot @Mode = 'Latest';         -- its newest run, pass or fail
        EXEC dbo.usp_ReportsWorkflowTracker_Pivot @Mode = 'LatestSuccess';  -- its newest clean run

    @Mode = 'Latest' answers "where does each lab stand right now"; 'LatestSuccess' answers "when was
    each lab last good", which is the run you compare a broken one against. Both give exactly one row
    per lab, newest first by Synced on. A lab with no qualifying run simply has no row - under
    'LatestSuccess' that means the lab has never had a clean run in the filtered window, which is
    itself the finding.

    A blank cell means that report never wrote a row for the run - which is NOT the same as a
    failure, and is worth chasing separately. Pass @ShowBlankAs to substitute a marker.

    The column list is built by dynamic SQL, so every report name goes through QUOTENAME. The
    caller's filter values are passed as parameters to sp_executesql and are never concatenated.
*/

USE [LRNMaster];
GO

CREATE OR ALTER PROCEDURE [dbo].[usp_ReportsWorkflowTracker_Pivot]
    @RunId                  VARCHAR(30)  = NULL,   -- one run, or all
    @LabId                  INT          = NULL,   -- one lab, or all
    @FromDate               DATE         = NULL,   -- filters on CreatedOn
    @ToDate                 DATE         = NULL,
    @IncludeInactiveReports BIT          = 0,      -- include IsActive = 0 report types as columns
    @ShowBlankAs            VARCHAR(50)  = NULL,   -- e.g. 'Not Run'; NULL leaves the cell empty
    @Mode                   VARCHAR(20)  = 'All'   -- All | Latest | LatestSuccess
AS
BEGIN
    SET NOCOUNT ON;

    SET @Mode = NULLIF(LTRIM(RTRIM(@Mode)), '');
    IF @Mode IS NULL SET @Mode = 'All';

    IF @Mode NOT IN ('All', 'Latest', 'LatestSuccess')
    BEGIN
        RAISERROR('usp_ReportsWorkflowTracker_Pivot: @Mode must be All, Latest or LatestSuccess (got ''%s'').', 16, 1, @Mode);
        RETURN;
    END

    /* ---- column list, straight from the master ---- */
    DECLARE @cols NVARCHAR(MAX);

    SELECT @cols = STRING_AGG(CAST(QUOTENAME(ReportTypeName) AS NVARCHAR(MAX)), N', ')
                       WITHIN GROUP (ORDER BY DisplayOrder, ReportTypeId)
    FROM   dbo.ReportTypeMaster
    WHERE  @IncludeInactiveReports = 1 OR IsActive = 1;

    IF @cols IS NULL
    BEGIN
        RAISERROR('usp_ReportsWorkflowTracker_Pivot: dbo.ReportTypeMaster has no matching report types.', 16, 1);
        RETURN;
    END

    /* ---- the same list again, wrapped so empty cells can carry a marker ---- */
    DECLARE @select NVARCHAR(MAX);

    SELECT @select = STRING_AGG(
               CAST(CASE WHEN @ShowBlankAs IS NULL
                         THEN N'p.' + QUOTENAME(ReportTypeName)
                         ELSE N'ISNULL(p.' + QUOTENAME(ReportTypeName) + N', @Blank)'
                    END + N' AS ' + QUOTENAME(ReportTypeName) AS NVARCHAR(MAX)), N',
        ')
           WITHIN GROUP (ORDER BY DisplayOrder, ReportTypeId)
    FROM   dbo.ReportTypeMaster
    WHERE  @IncludeInactiveReports = 1 OR IsActive = 1;

    /*
        The PIVOT source must contain ONLY the key columns plus ReportName/Status. Any extra column
        left in there silently becomes part of the implicit GROUP BY and splits a lab's run across
        several rows, so LabName / WeekFolder / Synced on are joined back on afterwards.
    */
    DECLARE @sql NVARCHAR(MAX) = N'
    WITH runs AS (
        SELECT  t.RunId,
                t.LabID,
                MAX(t.LabName)     AS LabName,
                MAX(t.WeekFolder)  AS WeekFolder,
                MAX(COALESCE(t.CompletedOn, t.CreatedOn)) AS SyncedOn,
                SUM(CASE WHEN t.Status = ''Success'' THEN 1 ELSE 0 END) AS Succeeded,
                SUM(CASE WHEN t.Status = ''Failed''  THEN 1 ELSE 0 END) AS Failed
        FROM    dbo.ReportsWorkflowTracker t
        WHERE  (@pRunId    IS NULL OR t.RunId = @pRunId)
          AND  (@pLabId    IS NULL OR t.LabID = @pLabId)
          AND  (@pFromDate IS NULL OR t.CreatedOn >= @pFromDate)
          AND  (@pToDate   IS NULL OR t.CreatedOn <  DATEADD(DAY, 1, @pToDate))
        GROUP BY t.RunId, t.LabID
    ),
    hdr AS (
        /*
            The WHERE runs before ROW_NUMBER, so under LatestSuccess rn = 1 is the newest CLEAN run
            rather than the newest run that happens to be clean.

            A clean run is one with nothing Failed and at least one Success. Skipped does not
            disqualify it - a report that was deliberately not run is not a failure - but a run that
            is entirely Skipped never succeeded at anything and is not a baseline worth comparing to.
        */
        SELECT  r.*,
                ROW_NUMBER() OVER (PARTITION BY r.LabID
                                   ORDER BY r.SyncedOn DESC, r.RunId DESC) AS rn
        FROM    runs r
        WHERE   @pMode <> ''LatestSuccess''
             OR (r.Failed = 0 AND r.Succeeded > 0)
    ),
    src AS (
        SELECT  t.RunId, t.LabID, t.ReportName, t.Status
        FROM    dbo.ReportsWorkflowTracker t
        WHERE  (@pRunId    IS NULL OR t.RunId = @pRunId)
          AND  (@pLabId    IS NULL OR t.LabID = @pLabId)
          AND  (@pFromDate IS NULL OR t.CreatedOn >= @pFromDate)
          AND  (@pToDate   IS NULL OR t.CreatedOn <  DATEADD(DAY, 1, @pToDate))
    )
    SELECT  h.LabName                                  AS [Lab],
            CONVERT(VARCHAR(10), h.SyncedOn, 101)      AS [Synced on],
            p.RunId                                    AS [RunID],
            h.WeekFolder                               AS [Week],
            ' + @select + N'
    FROM    src
    PIVOT  (MAX(Status) FOR ReportName IN (' + @cols + N')) AS p
    JOIN    hdr h
            ON  h.RunId = p.RunId
            AND h.LabID = p.LabID
            AND (@pMode = ''All'' OR h.rn = 1)   -- one row per lab in the other two modes
    ORDER BY CASE WHEN @pMode = ''All'' THEN NULL ELSE h.LabName END ASC,
             CASE WHEN @pMode = ''All'' THEN h.SyncedOn END DESC,
             h.LabName;';

    EXEC sp_executesql
         @sql,
         N'@pRunId VARCHAR(30), @pLabId INT, @pFromDate DATE, @pToDate DATE, @Blank VARCHAR(50), @pMode VARCHAR(20)',
         @pRunId    = @RunId,
         @pLabId    = @LabId,
         @pFromDate = @FromDate,
         @pToDate   = @ToDate,
         @Blank     = @ShowBlankAs,
         @pMode     = @Mode;
END
GO

GRANT EXECUTE ON [dbo].[usp_ReportsWorkflowTracker_Pivot] TO [public];
GO
GO

/* ---------- usp_ReportRunIdInfoLog_Get (read the run log back) ---------- */
GO
/*
    dbo.usp_ReportRunIdInfoLog_Get

    Reads the run log back. Send a RunId and get that run's whole trail in the order it happened;
    add @LogType to narrow it to the errors.

    CALL:
        EXEC dbo.usp_ReportRunIdInfoLog_Get @RunId = '20260801R0007';                     -- everything
        EXEC dbo.usp_ReportRunIdInfoLog_Get @RunId = '20260801R0007', @LogType = 'Error'; -- errors only
        EXEC dbo.usp_ReportRunIdInfoLog_Get @RunId = '20260801R0007', @LogType = 'Error,Warning';
        EXEC dbo.usp_ReportRunIdInfoLog_Get @LogType = 'Error', @FromDate = '2026-08-01'; -- across runs
        EXEC dbo.usp_ReportRunIdInfoLog_Get @RunId = '20260801R0007', @IncludeSummary = 1;

    @LogType NULL means every type - the caller does not have to name them to get all of them.
    It accepts a comma-separated list so error-and-warning triage is one call.

    Rows come back oldest first, which is how a run reads as a story: Start, the Info steps, then
    whatever went wrong. Pass @Newest = 1 to flip it for a 'what just broke' view.

    A typo'd @LogType is rejected rather than silently returning nothing - an empty result during
    triage is indistinguishable from a clean run, and that is the worst possible answer to be wrong
    about.
*/

USE [LRNMaster];
GO

CREATE OR ALTER PROCEDURE [dbo].[usp_ReportRunIdInfoLog_Get]
    @RunId          VARCHAR(30)  = NULL,   -- one run, or all runs when NULL
    @LogType        VARCHAR(200) = NULL,   -- 'Error', 'Error,Warning', or NULL for every type
    @ReportType     VARCHAR(100) = NULL,   -- e.g. 'Line Level'
    @SourceSystem   VARCHAR(100) = NULL,   -- lab name, or 'SharePoint'
    @FromDate       DATE         = NULL,   -- filters on CreatedOn
    @ToDate         DATE         = NULL,
    @Newest         BIT          = 0,      -- 1 = newest first
    @IncludeSummary BIT          = 0       -- 1 = also return a count per LogType
AS
BEGIN
    SET NOCOUNT ON;

    /* ---- the requested types, split and trimmed; empty table = no filter ---- */
    DECLARE @types TABLE ([LogType] VARCHAR(50) NOT NULL PRIMARY KEY);

    IF NULLIF(LTRIM(RTRIM(@LogType)), '') IS NOT NULL
    BEGIN
        INSERT INTO @types ([LogType])
        SELECT DISTINCT LTRIM(RTRIM(value))
        FROM   STRING_SPLIT(@LogType, ',')
        WHERE  NULLIF(LTRIM(RTRIM(value)), '') IS NOT NULL;

        /*
            Validate against what the log actually contains, not a hard-coded list - teams add log
            types over time and this must not become the reason a new one cannot be read back.
        */
        DECLARE @unknown VARCHAR(MAX), @known VARCHAR(MAX);

        SELECT @unknown = STRING_AGG(t.[LogType], ', ')
        FROM   @types t
        WHERE  NOT EXISTS (SELECT 1 FROM dbo.ReportRunIdInfoLog L WHERE L.LogType = t.[LogType]);

        IF @unknown IS NOT NULL
        BEGIN
            SELECT @known = STRING_AGG(CONVERT(VARCHAR(MAX), LogType), ', ')
            FROM   (SELECT DISTINCT LogType FROM dbo.ReportRunIdInfoLog) d;

            RAISERROR('usp_ReportRunIdInfoLog_Get: unknown @LogType (%s). Types present in the log: %s. Omit @LogType for all types.',
                      16, 1, @unknown, @known);
            RETURN;
        END
    END

    /* ---- the log ---- */
    SELECT  L.ReportRunIdInfoLogId,
            L.RunId,
            L.ReportType,
            L.SourceSystem,
            L.LogType,
            L.LogMessage,
            L.SourceFileName,
            L.CreatedOn,
            L.CreatedBy
    FROM    dbo.ReportRunIdInfoLog L
    WHERE  (@RunId        IS NULL OR L.RunId        = @RunId)
      AND  (@ReportType   IS NULL OR L.ReportType   = @ReportType)
      AND  (@SourceSystem IS NULL OR L.SourceSystem = @SourceSystem)
      AND  (@FromDate     IS NULL OR L.CreatedOn   >= @FromDate)
      AND  (@ToDate       IS NULL OR L.CreatedOn    < DATEADD(DAY, 1, @ToDate))
      AND  (NOT EXISTS (SELECT 1 FROM @types)
            OR L.LogType IN (SELECT [LogType] FROM @types))
    -- The unused direction is NULL for every row, so that key ties and falls through. Both CASE
    -- arms must be the same type: 0 vs CreatedOn is an operand clash (msg 206).
    ORDER BY CASE WHEN @Newest = 1 THEN NULL ELSE L.CreatedOn END ASC,
             CASE WHEN @Newest = 1 THEN L.CreatedOn ELSE NULL END DESC,
             CASE WHEN @Newest = 1 THEN -L.ReportRunIdInfoLogId ELSE L.ReportRunIdInfoLogId END ASC
    OPTION (RECOMPILE);   -- the filters vary per call; one cached plan would suit only one of them

    /* ---- optional second result set: how many of each type ---- */
    IF @IncludeSummary = 1
    BEGIN
        SELECT  L.LogType,
                COUNT(*)          AS [Entries],
                MIN(L.CreatedOn)  AS [FirstAt],
                MAX(L.CreatedOn)  AS [LastAt]
        FROM    dbo.ReportRunIdInfoLog L
        WHERE  (@RunId        IS NULL OR L.RunId        = @RunId)
          AND  (@ReportType   IS NULL OR L.ReportType   = @ReportType)
          AND  (@SourceSystem IS NULL OR L.SourceSystem = @SourceSystem)
          AND  (@FromDate     IS NULL OR L.CreatedOn   >= @FromDate)
          AND  (@ToDate       IS NULL OR L.CreatedOn    < DATEADD(DAY, 1, @ToDate))
          AND  (NOT EXISTS (SELECT 1 FROM @types)
                OR L.LogType IN (SELECT [LogType] FROM @types))
        GROUP BY L.LogType
        ORDER BY [Entries] DESC
        OPTION (RECOMPILE);
    END
END
GO

GRANT EXECUTE ON [dbo].[usp_ReportRunIdInfoLog_Get] TO [public];
GO
GO

/* ---------- Per-lab RunIds: R<YYYYMMDD><SHORT><NNNN> ---------- */
GO
/*
    Per-lab RunIds:  R<YYYYMMDD><SHORT><NNNN>     e.g. R20260803CRT0001

    Replaces the old global daily counter (20260801R0007), where every lab shared one sequence and
    the id said nothing about which lab it belonged to.

    The counter is per lab and CONTINUOUS - it never resets, so the number is that lab's lifetime run
    number. Certus's 44th run ever is R20260804CRT0044 whatever the date. Two labs running on the
    same day get their own sequences:

        R20260803CRT0041   R20260803NWL0016
        R20260803CRT0042   R20260804NWL0017
        R20260804CRT0043

    Old-format ids already in the log tables stay exactly as they are. The two shapes never collide -
    the new one starts with 'R' and the old one starts with a digit - so nothing needs migrating.

    Width: 1 + 8 + 3 + 4 = 16 characters against VARCHAR(30) columns, leaving room for the sequence
    to grow past 9999 (see the padding note in the procedure).

    Idempotent - safe to re-run.
*/

USE [LRNMaster];
GO

/* ------------------------------------------------------------------ *
 *  1.  dbo.Labs.ShortName - the code that goes in the RunId
 * ------------------------------------------------------------------ */

IF COL_LENGTH('dbo.Labs', 'ShortName') IS NULL
BEGIN
    ALTER TABLE [dbo].[Labs] ADD [ShortName] VARCHAR(10) NULL;
    PRINT 'dbo.Labs + ShortName';
END
GO

/* Two labs sharing a code would silently interleave their sequences. */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UQ_Labs_ShortName' AND object_id = OBJECT_ID('dbo.Labs'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX [UQ_Labs_ShortName]
        ON [dbo].[Labs] ([ShortName]) WHERE [ShortName] IS NOT NULL;
END
GO

/*
    Seeded by LabId, not by name: dbo.Labs spells them differently from the worker config
    ('Northwest' vs 'NorthWest', 'Augustus_Labs' vs 'Augustus'), and LabId is the identity the
    alignment work already settled on.
*/
MERGE dbo.Labs AS target
USING (VALUES
        ( 2, 'INH', 'InHealth'),
        ( 4, 'COV', 'Cove'),
        ( 6, 'PAL', 'PCRDx - AL'),
        ( 7, 'PCO', 'PCRDx - CO'),
        ( 9, 'RST', 'Rising Tides'),
        (10, 'BCT', 'BeechTree'),
        (12, 'PHY', 'Phi Life'),
        (13, 'PLA', 'PCR Labs of America'),
        (16, 'ELX', 'Elixir'),
        (18, 'CRT', 'Certus'),
        (23, 'NWL', 'Northwest'),
        (24, 'AUG', 'Augustus_Labs')
      ) AS source (LabId, ShortName, ExpectedName)
    ON target.LabId = source.LabId
WHEN MATCHED THEN
    UPDATE SET ShortName = source.ShortName;
GO

/* Anything active that can still not produce a RunId. */
IF EXISTS (SELECT 1 FROM dbo.Labs WHERE IsActive = 1 AND ShortName IS NULL AND LabId <> 999)
BEGIN
    PRINT 'WARNING - active labs with no ShortName (they cannot generate a RunId):';
    SELECT LabId, LabName FROM dbo.Labs WHERE IsActive = 1 AND ShortName IS NULL AND LabId <> 999;
END
GO

/* ------------------------------------------------------------------ *
 *  2.  dbo.LRN_RunIdSequence - one continuous counter per lab
 * ------------------------------------------------------------------ */

/*
    The old table was keyed on RunDate alone - one global counter that reset daily. That is a
    different thing from what we now store, so it is set aside rather than reshaped: the counters in
    it are meaningless under the new scheme, and keeping it makes the change reversible.
*/
IF OBJECT_ID('dbo.LRN_RunIdSequence', 'U') IS NOT NULL
   AND COL_LENGTH('dbo.LRN_RunIdSequence', 'LabShortName') IS NULL
BEGIN
    IF OBJECT_ID('dbo.LRN_RunIdSequence_Legacy', 'U') IS NOT NULL
        DROP TABLE dbo.LRN_RunIdSequence_Legacy;

    EXEC sp_rename 'dbo.LRN_RunIdSequence', 'LRN_RunIdSequence_Legacy';
    PRINT 'Old global counter set aside as dbo.LRN_RunIdSequence_Legacy';
END
GO

/*
    sp_rename moves the table but leaves its constraints named after the old one, so the new table
    cannot claim PK_LRN_RunIdSequence. Renaming the constraint is a separate step on purpose: if the
    table rename already happened on an earlier run, this still needs doing.
*/
IF OBJECT_ID('dbo.LRN_RunIdSequence_Legacy', 'U') IS NOT NULL
   AND EXISTS (SELECT 1 FROM sys.key_constraints
               WHERE name = 'PK_LRN_RunIdSequence'
                 AND parent_object_id = OBJECT_ID('dbo.LRN_RunIdSequence_Legacy'))
BEGIN
    EXEC sp_rename 'dbo.PK_LRN_RunIdSequence', 'PK_LRN_RunIdSequence_Legacy', 'OBJECT';
END
GO

IF OBJECT_ID('dbo.LRN_RunIdSequence', 'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[LRN_RunIdSequence]
    (
        [LabShortName] VARCHAR(10)  NOT NULL
            CONSTRAINT [PK_LRN_RunIdSequence] PRIMARY KEY CLUSTERED,
        [LastSeq]      INT          NOT NULL,
        [LastRunId]    VARCHAR(30)  NULL,   -- diagnostics: what the last allocation handed out
        [LastIssuedOn] DATETIME2(3) NULL
    );
    PRINT 'dbo.LRN_RunIdSequence created (per-lab, continuous)';
END
GO

/* ------------------------------------------------------------------ *
 *  3.  dbo.sp_LRN_NextRunId
 * ------------------------------------------------------------------ */

CREATE OR ALTER PROCEDURE [dbo].[sp_LRN_NextRunId]
    @RunId     VARCHAR(30) OUTPUT,
    @LabId     INT          = NULL,   -- preferred: unambiguous
    @LabName   VARCHAR(200) = NULL,   -- fallback when the caller only knows the name
    @ShortName VARCHAR(10)  = NULL    -- explicit override, skips the lookup
AS
BEGIN
    SET NOCOUNT ON;

    /* ---- resolve the lab code ---- */
    SET @ShortName = NULLIF(LTRIM(RTRIM(@ShortName)), '');

    IF @ShortName IS NULL AND @LabId IS NOT NULL
        SELECT @ShortName = ShortName FROM dbo.Labs WHERE LabId = @LabId;

    /*
        Name matching is deliberately loose - callers say 'NorthWest', dbo.Labs says 'Northwest',
        and the mapping JSONs use 'Augustus' against 'Augustus_Labs'. Case, spaces, underscores and
        hyphens are all noise here.
    */
    IF @ShortName IS NULL AND NULLIF(LTRIM(RTRIM(@LabName)), '') IS NOT NULL
    BEGIN
        DECLARE @needle VARCHAR(200) =
            UPPER(REPLACE(REPLACE(REPLACE(LTRIM(RTRIM(@LabName)), ' ', ''), '_', ''), '-', ''));

        SELECT TOP (1) @ShortName = ShortName
        FROM   dbo.Labs
        WHERE  ShortName IS NOT NULL
          AND  UPPER(REPLACE(REPLACE(REPLACE(LabName, ' ', ''), '_', ''), '-', '')) = @needle
        ORDER BY IsActive DESC, LabId;
    END

    /*
        Fail rather than invent a code. A RunId is written into every log table and into 12 lab
        databases; a wrong or placeholder one is permanent and would have to be unpicked by hand,
        whereas this stops the run with something the operator can fix in one UPDATE.
    */
    IF @ShortName IS NULL
    BEGIN
        RAISERROR('sp_LRN_NextRunId: no ShortName for LabId %d / LabName "%s". Set dbo.Labs.ShortName for that lab (see sql/LRNMaster/11_RunId_PerLab.sql).',
                  16, 1, @LabId, @LabName);
        RETURN;
    END

    /* ---- allocate the next number ---- */
    DECLARE @seq INT;

    BEGIN TRAN;

        -- Assignment-in-UPDATE: reads and increments under one lock, so two labs starting at the
        -- same instant cannot be handed the same number.
        UPDATE dbo.LRN_RunIdSequence WITH (UPDLOCK, HOLDLOCK)
           SET @seq         = LastSeq = LastSeq + 1,
               LastIssuedOn = SYSDATETIME()
         WHERE LabShortName = @ShortName;

        IF @@ROWCOUNT = 0
        BEGIN
            -- HOLDLOCK above range-locks the missing key, so this insert is not a race.
            INSERT dbo.LRN_RunIdSequence (LabShortName, LastSeq, LastIssuedOn)
            VALUES (@ShortName, 1, SYSDATETIME());

            SET @seq = 1;
        END

        /*
            Pad to 4, but never truncate. A continuous counter does eventually pass 9999, and
            RIGHT(...,4) would then start handing out numbers it had already used - so the id grows
            to five digits instead of silently colliding.
        */
        DECLARE @seqText VARCHAR(10) = CONVERT(VARCHAR(10), @seq);
        IF LEN(@seqText) < 4
            SET @seqText = RIGHT('0000' + @seqText, 4);

        SET @RunId = 'R' + CONVERT(VARCHAR(8), GETDATE(), 112) + @ShortName + @seqText;

        UPDATE dbo.LRN_RunIdSequence
           SET LastRunId = @RunId
         WHERE LabShortName = @ShortName;

    COMMIT;
END
GO

GRANT EXECUTE ON [dbo].[sp_LRN_NextRunId] TO [public];
GO

SELECT LabId, LabName, ShortName, IsActive FROM dbo.Labs WHERE ShortName IS NOT NULL ORDER BY ShortName;
GO
GO

PRINT 'LRNMaster deployment complete.';
GO
