USE [BeechTree_LRN];
GO

/* ClaimLevelData - generated by sql/generate_sql.py. Do not hand-edit. */
IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON s.schema_id = t.schema_id
               WHERE s.name = 'dbo' AND t.name = 'ClaimLevelData')
BEGIN
    CREATE TABLE [dbo].[ClaimLevelData]
    (
        [RecordId] BIGINT IDENTITY(1,1) NOT NULL
            CONSTRAINT [PK_ClaimLevelData] PRIMARY KEY CLUSTERED,
        [FileLogId] BIGINT NOT NULL,
        [RunId] VARCHAR(30) NOT NULL,
        [WeekFolder] NVARCHAR(200) NULL,
        [SourceFullPath] NVARCHAR(1000) NULL,
        [FileName] NVARCHAR(400) NULL,
        [FileType] VARCHAR(20) NOT NULL,
        [RowHash] CHAR(64) NOT NULL,
        [LabID] INT NOT NULL,
        [LabName] NVARCHAR(200) NOT NULL,
        [ClaimID] NVARCHAR(500) NULL,
        [AccessionNumber] NVARCHAR(500) NULL,
        [SourceFileID] NVARCHAR(500) NULL,
        [IngestedOn] NVARCHAR(500) NULL,
        [CsvRowHash] NVARCHAR(500) NULL,
        [PayerName_Raw] NVARCHAR(1000) NULL,
        [PayerName] NVARCHAR(1000) NULL,
        [Payer_Code] NVARCHAR(1000) NULL,
        [Payer_Common_Code] NVARCHAR(1000) NULL,
        [Payer_Group_Code] NVARCHAR(1000) NULL,
        [Global_Payer_ID] NVARCHAR(1000) NULL,
        [PayerType] NVARCHAR(1000) NULL,
        [BillingProvider] NVARCHAR(1000) NULL,
        [ReferringProvider] NVARCHAR(1000) NULL,
        [ClinicName] NVARCHAR(1000) NULL,
        [SalesRepname] NVARCHAR(1000) NULL,
        [PatientID] NVARCHAR(500) NULL,
        [PatientDOB] NVARCHAR(500) NULL,
        [DateofService] NVARCHAR(500) NULL,
        [ChargeEnteredDate] NVARCHAR(500) NULL,
        [FirstBilledDate] NVARCHAR(500) NULL,
        [Panelname] NVARCHAR(1000) NULL,
        [CPTCodeXUnitsXModifierOrginal] NVARCHAR(MAX) NULL,
        [CPTCodeXUnitsXModifier] NVARCHAR(MAX) NULL,
        [POS] NVARCHAR(500) NULL,
        [TOS] NVARCHAR(500) NULL,
        [ChargeAmount] NVARCHAR(500) NULL,
        [AllowedAmount] NVARCHAR(500) NULL,
        [InsurancePayment] NVARCHAR(500) NULL,
        [PatientPayment] NVARCHAR(500) NULL,
        [TotalPayments] NVARCHAR(500) NULL,
        [InsuranceAdjustments] NVARCHAR(500) NULL,
        [PatientAdjustments] NVARCHAR(500) NULL,
        [TotalAdjustments] NVARCHAR(500) NULL,
        [InsuranceBalance] NVARCHAR(500) NULL,
        [PatientBalance] NVARCHAR(500) NULL,
        [TotalBalance] NVARCHAR(500) NULL,
        [CheckDate] NVARCHAR(500) NULL,
        [ClaimStatus] NVARCHAR(1000) NULL,
        [DenialCode] NVARCHAR(500) NULL,
        [ICDCode] NVARCHAR(MAX) NULL,
        [DaystoDOS] NVARCHAR(500) NULL,
        [RollingDays] NVARCHAR(500) NULL,
        [DaystoBill] NVARCHAR(500) NULL,
        [DaystoPost] NVARCHAR(500) NULL,
        [ICDPointer] NVARCHAR(MAX) NULL,
        [PatientName] NVARCHAR(1000) NULL,
        [BilledUnbilled] NVARCHAR(500) NULL,
        [PaymentPercent] NVARCHAR(500) NULL,
        [Aging] NVARCHAR(500) NULL,
        [AgingBucket] NVARCHAR(500) NULL,
        [BilledWeek] NVARCHAR(500) NULL,
        [PostedWeek] NVARCHAR(500) NULL,
        [FullyPaidCount] NVARCHAR(500) NULL,
        [FullyPaidAmount] NVARCHAR(500) NULL,
        [AdjudicatedCount] NVARCHAR(500) NULL,
        [AdjudicatedAmount] NVARCHAR(500) NULL,
        [Days30Count] NVARCHAR(500) NULL,
        [Days30Amount] NVARCHAR(500) NULL,
        [Days60Count] NVARCHAR(500) NULL,
        [Days60Amount] NVARCHAR(500) NULL,
        [DOE_Year] NVARCHAR(500) NULL,
        [DOE_Month] NVARCHAR(500) NULL,
        [ClaimUID] NVARCHAR(500) NULL,
        [AgingDOE] NVARCHAR(500) NULL,
        [AgingDOS] NVARCHAR(500) NULL,
        [PanelNameLIS] NVARCHAR(1000) NULL,
        [PanelNameBasedOnCPT] NVARCHAR(1000) NULL,
        [InsertedDateTime] DATETIME2(3) NOT NULL
            CONSTRAINT [DF_ClaimLevelData_InsertedDateTime] DEFAULT (SYSDATETIME())
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_ClaimLevelData_RunId' AND object_id = OBJECT_ID('dbo.ClaimLevelData'))
    CREATE NONCLUSTERED INDEX [IX_ClaimLevelData_RunId] ON [dbo].[ClaimLevelData] ([RunId]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_ClaimLevelData_FileLogId' AND object_id = OBJECT_ID('dbo.ClaimLevelData'))
    CREATE NONCLUSTERED INDEX [IX_ClaimLevelData_FileLogId] ON [dbo].[ClaimLevelData] ([FileLogId]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_ClaimLevelData_Lab_FileType_Run' AND object_id = OBJECT_ID('dbo.ClaimLevelData'))
    CREATE NONCLUSTERED INDEX [IX_ClaimLevelData_Lab_FileType_Run] ON [dbo].[ClaimLevelData] ([LabID], [FileType], [RunId]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_ClaimLevelData_RowHash' AND object_id = OBJECT_ID('dbo.ClaimLevelData'))
    CREATE NONCLUSTERED INDEX [IX_ClaimLevelData_RowHash] ON [dbo].[ClaimLevelData] ([RowHash]);
GO

/* ClaimLevelData_Staging - load target for the staging+swap strategy. Same shape, no identity/indexes. */
IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON s.schema_id = t.schema_id
               WHERE s.name = 'dbo' AND t.name = 'ClaimLevelData_Staging')
BEGIN
    CREATE TABLE [dbo].[ClaimLevelData_Staging]
    (
        [FileLogId] BIGINT NOT NULL,
        [RunId] VARCHAR(30) NOT NULL,
        [WeekFolder] NVARCHAR(200) NULL,
        [SourceFullPath] NVARCHAR(1000) NULL,
        [FileName] NVARCHAR(400) NULL,
        [FileType] VARCHAR(20) NOT NULL,
        [RowHash] CHAR(64) NOT NULL,
        [LabID] INT NOT NULL,
        [LabName] NVARCHAR(200) NOT NULL,
        [ClaimID] NVARCHAR(500) NULL,
        [AccessionNumber] NVARCHAR(500) NULL,
        [SourceFileID] NVARCHAR(500) NULL,
        [IngestedOn] NVARCHAR(500) NULL,
        [CsvRowHash] NVARCHAR(500) NULL,
        [PayerName_Raw] NVARCHAR(1000) NULL,
        [PayerName] NVARCHAR(1000) NULL,
        [Payer_Code] NVARCHAR(1000) NULL,
        [Payer_Common_Code] NVARCHAR(1000) NULL,
        [Payer_Group_Code] NVARCHAR(1000) NULL,
        [Global_Payer_ID] NVARCHAR(1000) NULL,
        [PayerType] NVARCHAR(1000) NULL,
        [BillingProvider] NVARCHAR(1000) NULL,
        [ReferringProvider] NVARCHAR(1000) NULL,
        [ClinicName] NVARCHAR(1000) NULL,
        [SalesRepname] NVARCHAR(1000) NULL,
        [PatientID] NVARCHAR(500) NULL,
        [PatientDOB] NVARCHAR(500) NULL,
        [DateofService] NVARCHAR(500) NULL,
        [ChargeEnteredDate] NVARCHAR(500) NULL,
        [FirstBilledDate] NVARCHAR(500) NULL,
        [Panelname] NVARCHAR(1000) NULL,
        [CPTCodeXUnitsXModifierOrginal] NVARCHAR(MAX) NULL,
        [CPTCodeXUnitsXModifier] NVARCHAR(MAX) NULL,
        [POS] NVARCHAR(500) NULL,
        [TOS] NVARCHAR(500) NULL,
        [ChargeAmount] NVARCHAR(500) NULL,
        [AllowedAmount] NVARCHAR(500) NULL,
        [InsurancePayment] NVARCHAR(500) NULL,
        [PatientPayment] NVARCHAR(500) NULL,
        [TotalPayments] NVARCHAR(500) NULL,
        [InsuranceAdjustments] NVARCHAR(500) NULL,
        [PatientAdjustments] NVARCHAR(500) NULL,
        [TotalAdjustments] NVARCHAR(500) NULL,
        [InsuranceBalance] NVARCHAR(500) NULL,
        [PatientBalance] NVARCHAR(500) NULL,
        [TotalBalance] NVARCHAR(500) NULL,
        [CheckDate] NVARCHAR(500) NULL,
        [ClaimStatus] NVARCHAR(1000) NULL,
        [DenialCode] NVARCHAR(500) NULL,
        [ICDCode] NVARCHAR(MAX) NULL,
        [DaystoDOS] NVARCHAR(500) NULL,
        [RollingDays] NVARCHAR(500) NULL,
        [DaystoBill] NVARCHAR(500) NULL,
        [DaystoPost] NVARCHAR(500) NULL,
        [ICDPointer] NVARCHAR(MAX) NULL,
        [PatientName] NVARCHAR(1000) NULL,
        [BilledUnbilled] NVARCHAR(500) NULL,
        [PaymentPercent] NVARCHAR(500) NULL,
        [Aging] NVARCHAR(500) NULL,
        [AgingBucket] NVARCHAR(500) NULL,
        [BilledWeek] NVARCHAR(500) NULL,
        [PostedWeek] NVARCHAR(500) NULL,
        [FullyPaidCount] NVARCHAR(500) NULL,
        [FullyPaidAmount] NVARCHAR(500) NULL,
        [AdjudicatedCount] NVARCHAR(500) NULL,
        [AdjudicatedAmount] NVARCHAR(500) NULL,
        [Days30Count] NVARCHAR(500) NULL,
        [Days30Amount] NVARCHAR(500) NULL,
        [Days60Count] NVARCHAR(500) NULL,
        [Days60Amount] NVARCHAR(500) NULL,
        [DOE_Year] NVARCHAR(500) NULL,
        [DOE_Month] NVARCHAR(500) NULL,
        [ClaimUID] NVARCHAR(500) NULL,
        [AgingDOE] NVARCHAR(500) NULL,
        [AgingDOS] NVARCHAR(500) NULL,
        [PanelNameLIS] NVARCHAR(1000) NULL,
        [PanelNameBasedOnCPT] NVARCHAR(1000) NULL,
        [InsertedDateTime] DATETIME2(3) NOT NULL CONSTRAINT [DF_ClaimLevelData_Staging_InsertedDateTime] DEFAULT (SYSDATETIME())
    );
END
GO

/* Reconcile [ClaimLevelData] with the current mapping - additive only. */
IF COL_LENGTH('dbo.ClaimLevelData', 'ClaimID') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [ClaimID] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'ClaimID' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [ClaimID] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'AccessionNumber') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [AccessionNumber] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'AccessionNumber' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [AccessionNumber] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'SourceFileID') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [SourceFileID] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'SourceFileID' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [SourceFileID] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'IngestedOn') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [IngestedOn] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'IngestedOn' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [IngestedOn] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'CsvRowHash') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [CsvRowHash] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'CsvRowHash' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [CsvRowHash] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'PayerName_Raw') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [PayerName_Raw] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'PayerName_Raw' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [PayerName_Raw] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'PayerName') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [PayerName] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'PayerName' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [PayerName] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'Payer_Code') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [Payer_Code] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'Payer_Code' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [Payer_Code] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'Payer_Common_Code') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [Payer_Common_Code] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'Payer_Common_Code' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [Payer_Common_Code] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'Payer_Group_Code') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [Payer_Group_Code] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'Payer_Group_Code' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [Payer_Group_Code] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'Global_Payer_ID') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [Global_Payer_ID] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'Global_Payer_ID' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [Global_Payer_ID] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'PayerType') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [PayerType] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'PayerType' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [PayerType] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'BillingProvider') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [BillingProvider] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'BillingProvider' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [BillingProvider] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'ReferringProvider') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [ReferringProvider] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'ReferringProvider' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [ReferringProvider] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'ClinicName') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [ClinicName] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'ClinicName' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [ClinicName] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'SalesRepname') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [SalesRepname] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'SalesRepname' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [SalesRepname] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'PatientID') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [PatientID] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'PatientID' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [PatientID] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'PatientDOB') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [PatientDOB] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'PatientDOB' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [PatientDOB] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'DateofService') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [DateofService] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'DateofService' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [DateofService] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'ChargeEnteredDate') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [ChargeEnteredDate] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'ChargeEnteredDate' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [ChargeEnteredDate] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'FirstBilledDate') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [FirstBilledDate] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'FirstBilledDate' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [FirstBilledDate] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'Panelname') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [Panelname] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'Panelname' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [Panelname] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'CPTCodeXUnitsXModifierOrginal') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [CPTCodeXUnitsXModifierOrginal] NVARCHAR(MAX) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'CPTCodeXUnitsXModifierOrginal' AND c.max_length <> -1)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [CPTCodeXUnitsXModifierOrginal] NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'CPTCodeXUnitsXModifier') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [CPTCodeXUnitsXModifier] NVARCHAR(MAX) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'CPTCodeXUnitsXModifier' AND c.max_length <> -1)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [CPTCodeXUnitsXModifier] NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'POS') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [POS] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'POS' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [POS] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'TOS') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [TOS] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'TOS' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [TOS] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'ChargeAmount') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [ChargeAmount] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'ChargeAmount' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [ChargeAmount] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'AllowedAmount') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [AllowedAmount] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'AllowedAmount' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [AllowedAmount] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'InsurancePayment') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [InsurancePayment] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'InsurancePayment' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [InsurancePayment] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'PatientPayment') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [PatientPayment] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'PatientPayment' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [PatientPayment] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'TotalPayments') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [TotalPayments] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'TotalPayments' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [TotalPayments] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'InsuranceAdjustments') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [InsuranceAdjustments] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'InsuranceAdjustments' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [InsuranceAdjustments] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'PatientAdjustments') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [PatientAdjustments] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'PatientAdjustments' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [PatientAdjustments] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'TotalAdjustments') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [TotalAdjustments] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'TotalAdjustments' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [TotalAdjustments] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'InsuranceBalance') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [InsuranceBalance] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'InsuranceBalance' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [InsuranceBalance] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'PatientBalance') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [PatientBalance] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'PatientBalance' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [PatientBalance] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'TotalBalance') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [TotalBalance] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'TotalBalance' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [TotalBalance] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'CheckDate') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [CheckDate] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'CheckDate' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [CheckDate] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'ClaimStatus') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [ClaimStatus] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'ClaimStatus' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [ClaimStatus] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'DenialCode') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [DenialCode] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'DenialCode' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [DenialCode] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'ICDCode') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [ICDCode] NVARCHAR(MAX) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'ICDCode' AND c.max_length <> -1)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [ICDCode] NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'DaystoDOS') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [DaystoDOS] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'DaystoDOS' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [DaystoDOS] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'RollingDays') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [RollingDays] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'RollingDays' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [RollingDays] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'DaystoBill') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [DaystoBill] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'DaystoBill' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [DaystoBill] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'DaystoPost') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [DaystoPost] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'DaystoPost' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [DaystoPost] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'ICDPointer') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [ICDPointer] NVARCHAR(MAX) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'ICDPointer' AND c.max_length <> -1)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [ICDPointer] NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'PatientName') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [PatientName] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'PatientName' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [PatientName] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'BilledUnbilled') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [BilledUnbilled] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'BilledUnbilled' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [BilledUnbilled] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'PaymentPercent') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [PaymentPercent] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'PaymentPercent' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [PaymentPercent] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'Aging') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [Aging] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'Aging' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [Aging] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'AgingBucket') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [AgingBucket] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'AgingBucket' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [AgingBucket] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'BilledWeek') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [BilledWeek] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'BilledWeek' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [BilledWeek] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'PostedWeek') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [PostedWeek] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'PostedWeek' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [PostedWeek] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'FullyPaidCount') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [FullyPaidCount] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'FullyPaidCount' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [FullyPaidCount] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'FullyPaidAmount') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [FullyPaidAmount] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'FullyPaidAmount' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [FullyPaidAmount] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'AdjudicatedCount') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [AdjudicatedCount] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'AdjudicatedCount' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [AdjudicatedCount] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'AdjudicatedAmount') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [AdjudicatedAmount] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'AdjudicatedAmount' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [AdjudicatedAmount] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'Days30Count') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [Days30Count] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'Days30Count' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [Days30Count] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'Days30Amount') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [Days30Amount] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'Days30Amount' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [Days30Amount] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'Days60Count') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [Days60Count] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'Days60Count' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [Days60Count] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'Days60Amount') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [Days60Amount] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'Days60Amount' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [Days60Amount] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'DOE_Year') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [DOE_Year] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'DOE_Year' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [DOE_Year] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'DOE_Month') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [DOE_Month] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'DOE_Month' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [DOE_Month] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'ClaimUID') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [ClaimUID] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'ClaimUID' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [ClaimUID] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'AgingDOE') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [AgingDOE] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'AgingDOE' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [AgingDOE] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'AgingDOS') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [AgingDOS] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'AgingDOS' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [AgingDOS] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'PanelNameLIS') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [PanelNameLIS] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'PanelNameLIS' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [PanelNameLIS] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData', 'PanelNameBasedOnCPT') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData] ADD [PanelNameBasedOnCPT] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData')
           AND c.name = 'PanelNameBasedOnCPT' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData] ALTER COLUMN [PanelNameBasedOnCPT] NVARCHAR(1000) NULL;
GO

/* Reconcile [ClaimLevelData_Staging] with the current mapping - additive only. */
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'ClaimID') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [ClaimID] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'ClaimID' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [ClaimID] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'AccessionNumber') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [AccessionNumber] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'AccessionNumber' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [AccessionNumber] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'SourceFileID') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [SourceFileID] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'SourceFileID' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [SourceFileID] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'IngestedOn') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [IngestedOn] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'IngestedOn' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [IngestedOn] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'CsvRowHash') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [CsvRowHash] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'CsvRowHash' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [CsvRowHash] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'PayerName_Raw') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [PayerName_Raw] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'PayerName_Raw' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [PayerName_Raw] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'PayerName') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [PayerName] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'PayerName' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [PayerName] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'Payer_Code') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [Payer_Code] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'Payer_Code' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [Payer_Code] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'Payer_Common_Code') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [Payer_Common_Code] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'Payer_Common_Code' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [Payer_Common_Code] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'Payer_Group_Code') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [Payer_Group_Code] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'Payer_Group_Code' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [Payer_Group_Code] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'Global_Payer_ID') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [Global_Payer_ID] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'Global_Payer_ID' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [Global_Payer_ID] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'PayerType') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [PayerType] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'PayerType' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [PayerType] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'BillingProvider') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [BillingProvider] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'BillingProvider' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [BillingProvider] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'ReferringProvider') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [ReferringProvider] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'ReferringProvider' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [ReferringProvider] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'ClinicName') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [ClinicName] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'ClinicName' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [ClinicName] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'SalesRepname') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [SalesRepname] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'SalesRepname' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [SalesRepname] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'PatientID') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [PatientID] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'PatientID' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [PatientID] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'PatientDOB') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [PatientDOB] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'PatientDOB' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [PatientDOB] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'DateofService') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [DateofService] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'DateofService' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [DateofService] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'ChargeEnteredDate') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [ChargeEnteredDate] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'ChargeEnteredDate' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [ChargeEnteredDate] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'FirstBilledDate') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [FirstBilledDate] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'FirstBilledDate' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [FirstBilledDate] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'Panelname') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [Panelname] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'Panelname' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [Panelname] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'CPTCodeXUnitsXModifierOrginal') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [CPTCodeXUnitsXModifierOrginal] NVARCHAR(MAX) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'CPTCodeXUnitsXModifierOrginal' AND c.max_length <> -1)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [CPTCodeXUnitsXModifierOrginal] NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'CPTCodeXUnitsXModifier') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [CPTCodeXUnitsXModifier] NVARCHAR(MAX) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'CPTCodeXUnitsXModifier' AND c.max_length <> -1)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [CPTCodeXUnitsXModifier] NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'POS') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [POS] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'POS' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [POS] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'TOS') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [TOS] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'TOS' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [TOS] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'ChargeAmount') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [ChargeAmount] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'ChargeAmount' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [ChargeAmount] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'AllowedAmount') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [AllowedAmount] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'AllowedAmount' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [AllowedAmount] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'InsurancePayment') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [InsurancePayment] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'InsurancePayment' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [InsurancePayment] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'PatientPayment') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [PatientPayment] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'PatientPayment' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [PatientPayment] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'TotalPayments') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [TotalPayments] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'TotalPayments' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [TotalPayments] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'InsuranceAdjustments') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [InsuranceAdjustments] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'InsuranceAdjustments' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [InsuranceAdjustments] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'PatientAdjustments') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [PatientAdjustments] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'PatientAdjustments' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [PatientAdjustments] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'TotalAdjustments') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [TotalAdjustments] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'TotalAdjustments' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [TotalAdjustments] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'InsuranceBalance') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [InsuranceBalance] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'InsuranceBalance' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [InsuranceBalance] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'PatientBalance') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [PatientBalance] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'PatientBalance' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [PatientBalance] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'TotalBalance') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [TotalBalance] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'TotalBalance' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [TotalBalance] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'CheckDate') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [CheckDate] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'CheckDate' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [CheckDate] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'ClaimStatus') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [ClaimStatus] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'ClaimStatus' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [ClaimStatus] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'DenialCode') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [DenialCode] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'DenialCode' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [DenialCode] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'ICDCode') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [ICDCode] NVARCHAR(MAX) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'ICDCode' AND c.max_length <> -1)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [ICDCode] NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'DaystoDOS') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [DaystoDOS] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'DaystoDOS' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [DaystoDOS] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'RollingDays') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [RollingDays] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'RollingDays' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [RollingDays] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'DaystoBill') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [DaystoBill] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'DaystoBill' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [DaystoBill] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'DaystoPost') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [DaystoPost] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'DaystoPost' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [DaystoPost] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'ICDPointer') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [ICDPointer] NVARCHAR(MAX) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'ICDPointer' AND c.max_length <> -1)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [ICDPointer] NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'PatientName') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [PatientName] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'PatientName' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [PatientName] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'BilledUnbilled') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [BilledUnbilled] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'BilledUnbilled' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [BilledUnbilled] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'PaymentPercent') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [PaymentPercent] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'PaymentPercent' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [PaymentPercent] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'Aging') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [Aging] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'Aging' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [Aging] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'AgingBucket') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [AgingBucket] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'AgingBucket' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [AgingBucket] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'BilledWeek') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [BilledWeek] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'BilledWeek' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [BilledWeek] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'PostedWeek') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [PostedWeek] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'PostedWeek' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [PostedWeek] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'FullyPaidCount') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [FullyPaidCount] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'FullyPaidCount' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [FullyPaidCount] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'FullyPaidAmount') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [FullyPaidAmount] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'FullyPaidAmount' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [FullyPaidAmount] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'AdjudicatedCount') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [AdjudicatedCount] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'AdjudicatedCount' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [AdjudicatedCount] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'AdjudicatedAmount') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [AdjudicatedAmount] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'AdjudicatedAmount' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [AdjudicatedAmount] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'Days30Count') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [Days30Count] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'Days30Count' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [Days30Count] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'Days30Amount') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [Days30Amount] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'Days30Amount' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [Days30Amount] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'Days60Count') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [Days60Count] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'Days60Count' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [Days60Count] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'Days60Amount') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [Days60Amount] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'Days60Amount' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [Days60Amount] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'DOE_Year') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [DOE_Year] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'DOE_Year' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [DOE_Year] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'DOE_Month') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [DOE_Month] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'DOE_Month' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [DOE_Month] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'ClaimUID') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [ClaimUID] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'ClaimUID' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [ClaimUID] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'AgingDOE') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [AgingDOE] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'AgingDOE' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [AgingDOE] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'AgingDOS') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [AgingDOS] NVARCHAR(500) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'AgingDOS' AND c.max_length <> -1 AND c.max_length < 1000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [AgingDOS] NVARCHAR(500) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'PanelNameLIS') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [PanelNameLIS] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'PanelNameLIS' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [PanelNameLIS] NVARCHAR(1000) NULL;
GO
IF COL_LENGTH('dbo.ClaimLevelData_Staging', 'PanelNameBasedOnCPT') IS NULL
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ADD [PanelNameBasedOnCPT] NVARCHAR(1000) NULL;
IF EXISTS (SELECT 1 FROM sys.columns c WHERE c.object_id = OBJECT_ID('dbo.ClaimLevelData_Staging')
           AND c.name = 'PanelNameBasedOnCPT' AND c.max_length <> -1 AND c.max_length < 2000)
    ALTER TABLE [dbo].[ClaimLevelData_Staging] ALTER COLUMN [PanelNameBasedOnCPT] NVARCHAR(1000) NULL;
GO
