USE [BeechTree_LRN];
GO

/* ClaimLevelData - generated by sql/generate_sql.py. Do not hand-edit. */
IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON s.schema_id = t.schema_id
               WHERE s.name = 'dbo' AND t.name = 'ClaimLevelData')
BEGIN
    CREATE TABLE [dbo].[ClaimLevelData]
    (
        [RecordId] BIGINT IDENTITY(1,1) NOT NULL
            CONSTRAINT [PK_ClaimLevelData] PRIMARY KEY CLUSTERED,
        [FileLogId] BIGINT NOT NULL,
        [RunId] VARCHAR(30) NOT NULL,
        [WeekFolder] NVARCHAR(200) NULL,
        [SourceFullPath] NVARCHAR(1000) NULL,
        [FileName] NVARCHAR(400) NULL,
        [FileType] VARCHAR(20) NOT NULL,
        [RowHash] CHAR(64) NOT NULL,
        [LabID] INT NOT NULL,
        [LabName] NVARCHAR(200) NOT NULL,
        [ClaimID] NVARCHAR(255) NULL,
        [AccessionNumber] NVARCHAR(255) NULL,
        [SourceFileID] NVARCHAR(255) NULL,
        [IngestedOn] NVARCHAR(255) NULL,
        [CsvRowHash] NVARCHAR(255) NULL,
        [PayerName_Raw] NVARCHAR(500) NULL,
        [PayerName] NVARCHAR(500) NULL,
        [Payer_Code] NVARCHAR(500) NULL,
        [Payer_Common_Code] NVARCHAR(500) NULL,
        [Payer_Group_Code] NVARCHAR(500) NULL,
        [Global_Payer_ID] NVARCHAR(500) NULL,
        [PayerType] NVARCHAR(500) NULL,
        [BillingProvider] NVARCHAR(500) NULL,
        [ReferringProvider] NVARCHAR(500) NULL,
        [ClinicName] NVARCHAR(500) NULL,
        [SalesRepname] NVARCHAR(500) NULL,
        [PatientID] NVARCHAR(255) NULL,
        [PatientDOB] NVARCHAR(255) NULL,
        [DateofService] NVARCHAR(255) NULL,
        [ChargeEnteredDate] NVARCHAR(255) NULL,
        [FirstBilledDate] NVARCHAR(255) NULL,
        [Panelname] NVARCHAR(500) NULL,
        [CPTCodeXUnitsXModifierOrginal] NVARCHAR(255) NULL,
        [CPTCodeXUnitsXModifier] NVARCHAR(255) NULL,
        [POS] NVARCHAR(255) NULL,
        [TOS] NVARCHAR(255) NULL,
        [ChargeAmount] NVARCHAR(255) NULL,
        [AllowedAmount] NVARCHAR(255) NULL,
        [InsurancePayment] NVARCHAR(255) NULL,
        [PatientPayment] NVARCHAR(255) NULL,
        [TotalPayments] NVARCHAR(255) NULL,
        [InsuranceAdjustments] NVARCHAR(255) NULL,
        [PatientAdjustments] NVARCHAR(255) NULL,
        [TotalAdjustments] NVARCHAR(255) NULL,
        [InsuranceBalance] NVARCHAR(255) NULL,
        [PatientBalance] NVARCHAR(255) NULL,
        [TotalBalance] NVARCHAR(255) NULL,
        [CheckDate] NVARCHAR(255) NULL,
        [ClaimStatus] NVARCHAR(500) NULL,
        [DenialCode] NVARCHAR(255) NULL,
        [ICDCode] NVARCHAR(1000) NULL,
        [DaystoDOS] NVARCHAR(255) NULL,
        [RollingDays] NVARCHAR(255) NULL,
        [DaystoBill] NVARCHAR(255) NULL,
        [DaystoPost] NVARCHAR(255) NULL,
        [ICDPointer] NVARCHAR(1000) NULL,
        [PatientName] NVARCHAR(500) NULL,
        [BilledUnbilled] NVARCHAR(255) NULL,
        [PaymentPercent] NVARCHAR(255) NULL,
        [Aging] NVARCHAR(255) NULL,
        [AgingBucket] NVARCHAR(255) NULL,
        [BilledWeek] NVARCHAR(255) NULL,
        [PostedWeek] NVARCHAR(255) NULL,
        [FullyPaidCount] NVARCHAR(255) NULL,
        [FullyPaidAmount] NVARCHAR(255) NULL,
        [AdjudicatedCount] NVARCHAR(255) NULL,
        [AdjudicatedAmount] NVARCHAR(255) NULL,
        [Days30Count] NVARCHAR(255) NULL,
        [Days30Amount] NVARCHAR(255) NULL,
        [Days60Count] NVARCHAR(255) NULL,
        [Days60Amount] NVARCHAR(255) NULL,
        [DOE_Year] NVARCHAR(255) NULL,
        [DOE_Month] NVARCHAR(255) NULL,
        [InsertedDateTime] DATETIME2(3) NOT NULL
            CONSTRAINT [DF_ClaimLevelData_InsertedDateTime] DEFAULT (SYSDATETIME())
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_ClaimLevelData_RunId' AND object_id = OBJECT_ID('dbo.ClaimLevelData'))
    CREATE NONCLUSTERED INDEX [IX_ClaimLevelData_RunId] ON [dbo].[ClaimLevelData] ([RunId]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_ClaimLevelData_FileLogId' AND object_id = OBJECT_ID('dbo.ClaimLevelData'))
    CREATE NONCLUSTERED INDEX [IX_ClaimLevelData_FileLogId] ON [dbo].[ClaimLevelData] ([FileLogId]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_ClaimLevelData_Lab_FileType_Run' AND object_id = OBJECT_ID('dbo.ClaimLevelData'))
    CREATE NONCLUSTERED INDEX [IX_ClaimLevelData_Lab_FileType_Run] ON [dbo].[ClaimLevelData] ([LabID], [FileType], [RunId]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_ClaimLevelData_RowHash' AND object_id = OBJECT_ID('dbo.ClaimLevelData'))
    CREATE NONCLUSTERED INDEX [IX_ClaimLevelData_RowHash] ON [dbo].[ClaimLevelData] ([RowHash]);
GO

/* ClaimLevelData_Staging - load target for the staging+swap strategy. Same shape, no identity/indexes. */
IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON s.schema_id = t.schema_id
               WHERE s.name = 'dbo' AND t.name = 'ClaimLevelData_Staging')
BEGIN
    CREATE TABLE [dbo].[ClaimLevelData_Staging]
    (
        [FileLogId] BIGINT NOT NULL,
        [RunId] VARCHAR(30) NOT NULL,
        [WeekFolder] NVARCHAR(200) NULL,
        [SourceFullPath] NVARCHAR(1000) NULL,
        [FileName] NVARCHAR(400) NULL,
        [FileType] VARCHAR(20) NOT NULL,
        [RowHash] CHAR(64) NOT NULL,
        [LabID] INT NOT NULL,
        [LabName] NVARCHAR(200) NOT NULL,
        [ClaimID] NVARCHAR(255) NULL,
        [AccessionNumber] NVARCHAR(255) NULL,
        [SourceFileID] NVARCHAR(255) NULL,
        [IngestedOn] NVARCHAR(255) NULL,
        [CsvRowHash] NVARCHAR(255) NULL,
        [PayerName_Raw] NVARCHAR(500) NULL,
        [PayerName] NVARCHAR(500) NULL,
        [Payer_Code] NVARCHAR(500) NULL,
        [Payer_Common_Code] NVARCHAR(500) NULL,
        [Payer_Group_Code] NVARCHAR(500) NULL,
        [Global_Payer_ID] NVARCHAR(500) NULL,
        [PayerType] NVARCHAR(500) NULL,
        [BillingProvider] NVARCHAR(500) NULL,
        [ReferringProvider] NVARCHAR(500) NULL,
        [ClinicName] NVARCHAR(500) NULL,
        [SalesRepname] NVARCHAR(500) NULL,
        [PatientID] NVARCHAR(255) NULL,
        [PatientDOB] NVARCHAR(255) NULL,
        [DateofService] NVARCHAR(255) NULL,
        [ChargeEnteredDate] NVARCHAR(255) NULL,
        [FirstBilledDate] NVARCHAR(255) NULL,
        [Panelname] NVARCHAR(500) NULL,
        [CPTCodeXUnitsXModifierOrginal] NVARCHAR(255) NULL,
        [CPTCodeXUnitsXModifier] NVARCHAR(255) NULL,
        [POS] NVARCHAR(255) NULL,
        [TOS] NVARCHAR(255) NULL,
        [ChargeAmount] NVARCHAR(255) NULL,
        [AllowedAmount] NVARCHAR(255) NULL,
        [InsurancePayment] NVARCHAR(255) NULL,
        [PatientPayment] NVARCHAR(255) NULL,
        [TotalPayments] NVARCHAR(255) NULL,
        [InsuranceAdjustments] NVARCHAR(255) NULL,
        [PatientAdjustments] NVARCHAR(255) NULL,
        [TotalAdjustments] NVARCHAR(255) NULL,
        [InsuranceBalance] NVARCHAR(255) NULL,
        [PatientBalance] NVARCHAR(255) NULL,
        [TotalBalance] NVARCHAR(255) NULL,
        [CheckDate] NVARCHAR(255) NULL,
        [ClaimStatus] NVARCHAR(500) NULL,
        [DenialCode] NVARCHAR(255) NULL,
        [ICDCode] NVARCHAR(1000) NULL,
        [DaystoDOS] NVARCHAR(255) NULL,
        [RollingDays] NVARCHAR(255) NULL,
        [DaystoBill] NVARCHAR(255) NULL,
        [DaystoPost] NVARCHAR(255) NULL,
        [ICDPointer] NVARCHAR(1000) NULL,
        [PatientName] NVARCHAR(500) NULL,
        [BilledUnbilled] NVARCHAR(255) NULL,
        [PaymentPercent] NVARCHAR(255) NULL,
        [Aging] NVARCHAR(255) NULL,
        [AgingBucket] NVARCHAR(255) NULL,
        [BilledWeek] NVARCHAR(255) NULL,
        [PostedWeek] NVARCHAR(255) NULL,
        [FullyPaidCount] NVARCHAR(255) NULL,
        [FullyPaidAmount] NVARCHAR(255) NULL,
        [AdjudicatedCount] NVARCHAR(255) NULL,
        [AdjudicatedAmount] NVARCHAR(255) NULL,
        [Days30Count] NVARCHAR(255) NULL,
        [Days30Amount] NVARCHAR(255) NULL,
        [Days60Count] NVARCHAR(255) NULL,
        [Days60Amount] NVARCHAR(255) NULL,
        [DOE_Year] NVARCHAR(255) NULL,
        [DOE_Month] NVARCHAR(255) NULL,
        [InsertedDateTime] DATETIME2(3) NOT NULL CONSTRAINT [DF_ClaimLevelData_Staging_InsertedDateTime] DEFAULT (SYSDATETIME())
    );
END
GO
